changelog:
  categories:
    - title: "🎉 New Features"
      labels:
        - "feature"

    - title: "❤️ Improvements"
      labels:
        - "enhancement"

    - title: "🛠️ Bugfixes"
      labels:
        - "bug"
