#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Error: a single argument is required"
  exit 1
fi

function start_server () {
  echo ""
  echo "Starting the server..."
  echo ""

  # Run setup to make sure database is up to date
  python -m setup
  
  # Start gunicorn
  exec gunicorn \
    -k uvicorn.workers.UvicornWorker \
    --log-level warning \
    -b :80 \
    server.server:app
}

function stop_server () {
  echo ""
  echo "SIGTERM signal received. Shutting down..."
  echo ""
  pid=$(ps aux | grep 'gunicorn' | awk '{print $2}')
  kill -TERM $pid 2> /dev/null
  exit 0
}

function reload_server () {
  echo ""
  echo "Reloading the server..."
  echo ""
  pid=$(ps aux | grep 'gunicorn' | awk '{print $2}')
  kill -HUP $pid 2> /dev/null
  exit 0
}

trap stop_server SIGTERM SIGINT


if [ $1 = "start" ]; then
  start_server
elif [ $1 = "stop" ]; then
  stop_server
elif [ $1 = "reload" ]; then
  reload_server
else
  echo ""
  echo "Error: invalid argument '$1'. Expected 'start' or 'reload'"
  echo ""
  exit 1
fi
