import { Dialog, InputText, Button } from '@components';
import { getErrorDetail } from '@lib/utils';
import React, { useState } from 'react';
import { toast } from 'react-toastify';
import styled from 'styled-components';

import nebula from '@/nebula';

const SubRow = styled.div`
  display: flex;
  flex-direction: row;
  gap: 8px;
  align-items: center;
`;

const keyInputStyle: React.CSSProperties = {
  flexGrow: 1,
  fontFamily: 'monospace',
  fontStyle: 'normal',
  textAlign: 'center',
};

interface ApiKeyPickerProps {
  // Keys are generated by the server, so the user must be saved first
  userId?: number;
  apiKeyPreview?: string;
  onCreated: () => void;
}

const ApiKeyPicker: React.FC<ApiKeyPickerProps> = ({
  userId,
  apiKeyPreview,
  onCreated,
}) => {
  const [dialogVisible, setDialogVisible] = useState(false);
  const [newKey, setNewKey] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const closeDialog = () => {
    setDialogVisible(false);
    setNewKey(null);
  };

  const generateKey = () => {
    if (!userId) return;
    setGenerating(true);
    nebula
      .usersRegenerateApiKey({ path: { user_id: userId }, throwOnError: true })
      .then((res) => {
        setNewKey(res.data.api_key);
        onCreated();
      })
      .catch((err: unknown) => {
        toast.error(`Unable to create API key: ${getErrorDetail(err)}`);
      })
      .finally(() => {
        setGenerating(false);
      });
  };

  const dialog = dialogVisible && (
    <Dialog
      onHide={closeDialog}
      style={{ width: 550 }}
      header="Create API key"
      footer={
        newKey ? (
          <Button icon="check" label="Done" onClick={closeDialog} />
        ) : (
          <>
            <Button icon="close" label="Cancel" onClick={closeDialog} />
            <Button
              icon="key"
              label="Create"
              onClick={generateKey}
              disabled={generating}
            />
          </>
        )
      }
    >
      {newKey ? (
        <>
          <p>
            Copy the key and store it in a safe place. You will not be able to retrieve
            it later.
          </p>
          <SubRow>
            <InputText
              value={newKey}
              readOnly
              onChange={() => {
                // read-only field
              }}
              style={keyInputStyle}
              onDoubleClick={(e) => {
                (e.target as HTMLInputElement).select();
              }}
            />
            <Button
              icon="content_copy"
              tooltip="Copy to clipboard"
              onClick={() => {
                void navigator.clipboard.writeText(newKey);
                toast.success('Copied to clipboard');
              }}
            />
          </SubRow>
        </>
      ) : (
        <p>
          A new API key will be created for this user. If the user already has a key, it
          stops working immediately.
        </p>
      )}
    </Dialog>
  );

  return (
    <>
      <InputText value={apiKeyPreview} readOnly style={keyInputStyle} />
      <Button
        icon="key"
        label="Create API key"
        tooltip={userId ? undefined : 'Save the user first'}
        style={{ maxWidth: 150 }}
        disabled={!userId}
        onClick={() => {
          setDialogVisible(true);
        }}
      />
      {dialog}
    </>
  );
};

export default ApiKeyPicker;
