// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ActionsData,
  ActionsErrors,
  ActionsResponses,
  ApplySchedulingTemplateData,
  ApplySchedulingTemplateErrors,
  ApplySchedulingTemplateResponses,
  BrowseData,
  BrowseErrors,
  BrowseResponses,
  DeleteData,
  DeleteErrors,
  DeleteResponses,
  GetAuxData,
  GetAuxErrors,
  GetAuxResponses,
  GetData,
  GetErrors,
  GetProxyInfoData,
  GetProxyInfoErrors,
  GetProxyInfoResponses,
  GetResponses,
  GetTranscriptionData,
  GetTranscriptionErrors,
  GetTranscriptionResponses,
  InitData,
  InitErrors,
  InitResponses,
  InvalidateSessionData,
  InvalidateSessionErrors,
  InvalidateSessionResponses,
  JobsData,
  JobsErrors,
  JobsResponses,
  ListSchedulingTemplatesData,
  ListSchedulingTemplatesErrors,
  ListSchedulingTemplatesResponses,
  ListSessionsData,
  ListSessionsErrors,
  ListSessionsResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  LoginBackgroundApiLoginBackgroundJpgGetData,
  LoginBackgroundApiLoginBackgroundJpgGetResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  OpsData,
  OpsErrors,
  OpsResponses,
  OrderData,
  OrderErrors,
  OrderResponses,
  PasswordData,
  PasswordErrors,
  PasswordResetCallbackData,
  PasswordResetCallbackErrors,
  PasswordResetCallbackResponses,
  PasswordResetData,
  PasswordResetErrors,
  PasswordResetResponses,
  PasswordResponses,
  PlayoutData,
  PlayoutErrors,
  PlayoutResponses,
  ProxyData,
  ProxyErrors,
  ProxyResponses,
  RundownData,
  RundownErrors,
  RundownResponses,
  SaveTranscriptionData,
  SaveTranscriptionErrors,
  SaveTranscriptionResponses,
  SaveUserData,
  SaveUserErrors,
  SaveUserResponses,
  SchedulerData,
  SchedulerErrors,
  SchedulerResponses,
  SendData,
  SendErrors,
  SendInvitationEmailData,
  SendInvitationEmailErrors,
  SendInvitationEmailResponses,
  SendResponses,
  ServicesData,
  ServicesErrors,
  ServicesResponses,
  SetData,
  SetErrors,
  SetResponses,
  SolveData,
  SolveErrors,
  SolveResponses,
  SsoCallbackData,
  SsoCallbackErrors,
  SsoCallbackResponses,
  SsoLoginData,
  SsoLoginErrors,
  SsoLoginResponses,
  StatsStoragesData,
  StatsStoragesErrors,
  StatsStoragesResponses,
  TokenExchangeData,
  TokenExchangeErrors,
  TokenExchangeResponses,
  UploadData,
  UploadErrors,
  UploadResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login Background
 *
 * Serve the login background image.
 */
export const loginBackgroundApiLoginBackgroundJpgGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LoginBackgroundApiLoginBackgroundJpgGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    LoginBackgroundApiLoginBackgroundJpgGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/login-background.jpg',
    ...options,
  });

/**
 * Get Storage Usage Statistics
 *
 * Get a list of objects
 */
export const statsStorages = <ThrowOnError extends boolean = false>(
  options?: Options<StatsStoragesData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    StatsStoragesResponses,
    StatsStoragesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/stats/storages',
    ...options,
  });

/**
 * Get Rundown
 *
 * Retrieve the rundown for a specified channel and date.
 *
 * The rundown is a list of items scheduled for broadcast on a given day.
 * Items are ordered by their start time and include metadata such as
 * scheduled time and actual broadcast time. During the broadcast, the
 * actual time is updated to reflect the real broadcast time.
 *
 * The rundown also includes non-playable items like blocks, placeholders,
 * and loop markers.
 *
 * The date should be specified in the format YYYY-MM-DD, considering the
 * channel's start time as configured. If no date is specified, the current
 * date is used.
 */
export const rundown = <ThrowOnError extends boolean = false>(
  options: Options<RundownData, ThrowOnError>
) =>
  (options.client ?? client).post<RundownResponses, RundownErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/rundown',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Manage Services
 *
 * List and control installed services.
 *
 * This endpoint allows users to list all installed services and control their state.
 * Users can start, stop, or toggle the autostart setting of a service by providing
 * the respective service ID in the request.
 */
export const services = <ThrowOnError extends boolean = false>(
  options: Options<ServicesData, ThrowOnError>
) =>
  (options.client ?? client).post<ServicesResponses, ServicesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/services',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Transcription
 *
 * Return a transcription of an asset
 */
export const getTranscription = <ThrowOnError extends boolean = false>(
  options: Options<GetTranscriptionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GetTranscriptionResponses,
    GetTranscriptionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/get_transcription',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Save Transcription
 *
 * Save a transcription for an asset
 */
export const saveTranscription = <ThrowOnError extends boolean = false>(
  options: Options<SaveTranscriptionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveTranscriptionResponses,
    SaveTranscriptionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/save_transcription',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Browse Assets
 *
 * Browse the assets database.
 */
export const browse = <ThrowOnError extends boolean = false>(
  options: Options<BrowseData, ThrowOnError>
) =>
  (options.client ?? client).post<BrowseResponses, BrowseErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/browse',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User List
 *
 * Get a list of users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).post<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/list-users',
    ...options,
  });

/**
 * Save User
 *
 * Save user data
 */
export const saveUser = <ThrowOnError extends boolean = false>(
  options: Options<SaveUserData, ThrowOnError>
) =>
  (options.client ?? client).post<SaveUserResponses, SaveUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/save-user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Send Invitation Email
 *
 * Handle sending an invitation email to the specified user.
 */
export const sendInvitationEmail = <ThrowOnError extends boolean = false>(
  options: Options<SendInvitationEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SendInvitationEmailResponses,
    SendInvitationEmailErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/send-invitation-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Objects
 *
 * Delete one or multiple objects from the database
 */
export const delete_ = <ThrowOnError extends boolean = false>(
  options: Options<DeleteData, ThrowOnError>
) =>
  (options.client ?? client).post<DeleteResponses, DeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Aux Data
 *
 * Retrieve aux data for a given object.
 */
export const getAux = <ThrowOnError extends boolean = false>(
  options: Options<GetAuxData, ThrowOnError>
) =>
  (options.client ?? client).post<GetAuxResponses, GetAuxErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/get-aux',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Objects
 *
 * Get a list of objects
 */
export const get = <ThrowOnError extends boolean = false>(
  options: Options<GetData, ThrowOnError>
) =>
  (options.client ?? client).post<GetResponses, GetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/get',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Operations
 *
 * Create or update multiple objects in one requests.
 */
export const ops = <ThrowOnError extends boolean = false>(
  options: Options<OpsData, ThrowOnError>
) =>
  (options.client ?? client).post<OpsResponses, OpsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ops',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Metadata
 *
 * Create or update an object.
 */
export const set = <ThrowOnError extends boolean = false>(
  options: Options<SetData, ThrowOnError>
) =>
  (options.client ?? client).post<SetResponses, SetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/set',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Order Items
 *
 * Set the order of items of a rundown
 */
export const order = <ThrowOnError extends boolean = false>(
  options: Options<OrderData, ThrowOnError>
) =>
  (options.client ?? client).post<OrderResponses, OrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/order',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Solve Rundown Placeholder
 *
 * Solve a rundown placeholder
 */
export const solve = <ThrowOnError extends boolean = false>(
  options: Options<SolveData, ThrowOnError>
) =>
  (options.client ?? client).post<SolveResponses, SolveErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/solve',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Apply Scheduling Template
 *
 * Apply a template to a channel
 */
export const applySchedulingTemplate = <ThrowOnError extends boolean = false>(
  options: Options<ApplySchedulingTemplateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ApplySchedulingTemplateResponses,
    ApplySchedulingTemplateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/apply-scheduling-template',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Scheduling Templates
 *
 * List available scheduling templates
 */
export const listSchedulingTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<ListSchedulingTemplatesData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    ListSchedulingTemplatesResponses,
    ListSchedulingTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/list-scheduling-templates',
    ...options,
  });

/**
 * Playout Control
 *
 * Control a playout server
 */
export const playout = <ThrowOnError extends boolean = false>(
  options: Options<PlayoutData, ThrowOnError>
) =>
  (options.client ?? client).post<PlayoutResponses, PlayoutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/playout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Login
 *
 * Login using a username and password
 *
 * This request will return an access token that can be used in the
 * Authorization header for the subsequent requests.
 * If the login fails, request will return 401 Unauthorized.
 *
 * If the login fails too many (configurable) times,
 * the IP address will be banned for a certain amount of time (configurable).
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Log out the current user.
 *
 * This request will invalidate the access token used in the Authorization header.
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/logout',
    ...options,
  });

/**
 * Password Reset Request
 *
 * Request a password reset for the given email
 */
export const passwordReset = <ThrowOnError extends boolean = false>(
  options: Options<PasswordResetData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PasswordResetResponses,
    PasswordResetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/password-reset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Password Reset Callback
 *
 * Reset the password using the token from the password reset email
 */
export const passwordResetCallback = <ThrowOnError extends boolean = false>(
  options: Options<PasswordResetCallbackData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PasswordResetCallbackResponses,
    PasswordResetCallbackErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/password-reset-callback',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Sso Login
 *
 * Redirect the user to the SSO provider's login page
 */
export const ssoLogin = <ThrowOnError extends boolean = false>(
  options: Options<SsoLoginData, ThrowOnError>
) =>
  (options.client ?? client).get<SsoLoginResponses, SsoLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/sso/login/{provider}',
    ...options,
  });

/**
 * Sso Login Callback
 *
 * Handle the callback from the SSO provider and log in the user
 */
export const ssoCallback = <ThrowOnError extends boolean = false>(
  options: Options<SsoCallbackData, ThrowOnError>
) =>
  (options.client ?? client).get<SsoCallbackResponses, SsoCallbackErrors, ThrowOnError>(
    {
      responseType: 'json',
      url: '/api/sso/callback/{provider}',
      ...options,
    }
  );

/**
 * Set Password
 *
 * Set a new password for the current (or a given) user.
 *
 * Normal users can only change their own password.
 *
 * In order to set a password for another user,
 * the current user must be an admin, otherwise a 403 error is returned.
 */
export const password = <ThrowOnError extends boolean = false>(
  options: Options<PasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<PasswordResponses, PasswordErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Token Exchange
 *
 * Exchange a transient access token for a normal one
 *
 * This request will exchange an access token for a new one.
 * The original access token will be invalidated.
 */
export const tokenExchange = <ThrowOnError extends boolean = false>(
  options: Options<TokenExchangeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TokenExchangeResponses,
    TokenExchangeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/token-exchange',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Server Info
 *
 * Initial client request to ensure user is logged in.
 *
 * If a valid access token is provided, user information
 * and Nebula settings are returned. If no access token is
 * provided, only the message of the day and OAuth2 options
 * are returned.
 */
export const init = <ThrowOnError extends boolean = false>(
  options?: Options<InitData, ThrowOnError>
) =>
  (options?.client ?? client).post<InitResponses, InitErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/init',
    ...options,
  });

/**
 * Scheduler
 *
 * Retrieve or update the schedule for a channel
 *
 * This endpoint handles chanel macro-scheduling,
 * including the creation, modification, and deletion of playout events.
 *
 * Schedule is represented as a list of events, typically for one week.
 */
export const scheduler = <ThrowOnError extends boolean = false>(
  options: Options<SchedulerData, ThrowOnError>
) =>
  (options.client ?? client).post<SchedulerResponses, SchedulerErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/scheduler',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Proxy Info
 *
 * Get proxy info for a given asset.
 */
export const getProxyInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetProxyInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProxyInfoResponses,
    GetProxyInfoErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/proxy/{id_asset}/info',
    ...options,
  });

/**
 * Serve Proxy
 *
 * Serve a low-res (proxy) media for a given asset.
 *
 * This endpoint supports range requests, so it is possible to use
 * the file in media players that support HTTPS pseudo-streaming.
 */
export const proxy = <ThrowOnError extends boolean = false>(
  options: Options<ProxyData, ThrowOnError>
) =>
  (options.client ?? client).get<ProxyResponses, ProxyErrors, ThrowOnError>({
    responseType: 'json',
    url: '/proxy/{id_asset}',
    ...options,
  });

/**
 * Get Objects
 *
 * Upload a media file for a given asset.
 *
 * This endpoint is used by the web frontend to upload media files.
 */
export const upload = <ThrowOnError extends boolean = false>(
  options: Options<UploadData, ThrowOnError>
) =>
  (options.client ?? client).post<UploadResponses, UploadErrors, ThrowOnError>({
    responseType: 'json',
    url: '/upload/{id_asset}',
    ...options,
  });

/**
 * Invalidate Session
 *
 * Invalidate a user session.
 *
 * This endpoint is used to invalidate an user session. It can be used
 * to remotely log out a user. If the user is an admin, it can also be
 * used to log out other users.
 */
export const invalidateSession = <ThrowOnError extends boolean = false>(
  options: Options<InvalidateSessionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    InvalidateSessionResponses,
    InvalidateSessionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/invalidate-session',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Sessions
 *
 * List user sessions.
 */
export const listSessions = <ThrowOnError extends boolean = false>(
  options: Options<ListSessionsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ListSessionsResponses,
    ListSessionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/list-sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Available Actions
 *
 * Get available actions for given list of assets
 *
 * Every action is evaluated for each asset using the `allow_if` condition
 * in the action settings and only returned if the condition is true for all assets.
 *
 * This allows to start jobs on multiple assets at once.
 */
export const actions = <ThrowOnError extends boolean = false>(
  options: Options<ActionsData, ThrowOnError>
) =>
  (options.client ?? client).post<ActionsResponses, ActionsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/actions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Manage Jobs
 *
 * Get list of jobs, abort or restart them
 */
export const jobs = <ThrowOnError extends boolean = false>(
  options: Options<JobsData, ThrowOnError>
) =>
  (options.client ?? client).post<JobsResponses, JobsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Send To
 *
 * Create jobs for a given list of assets.
 */
export const send = <ThrowOnError extends boolean = false>(
  options: Options<SendData, ThrowOnError>
) =>
  (options.client ?? client).post<SendResponses, SendErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
