// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * AcceptModel
 */
export type AcceptModel = {
  /**
   * Folders
   *
   * List of folder IDs
   */
  folders?: Array<number> | null;
  /**
   * Content types
   *
   * List of content types that are accepted. None means all types are accepted.
   */
  content_types?: Array<ContentType> | null;
  /**
   * Media types
   *
   * List of media types that are accepted. None means all types are accepted.
   */
  media_types?: Array<MediaType> | null;
};

/**
 * ActionItemModel
 */
export type ActionItemModel = {
  /**
   * Action ID
   */
  id: number;
  /**
   * Action name
   */
  name: string;
};

/**
 * AgentInfo
 */
export type AgentInfo = {
  /**
   * Platform
   */
  platform?: string | null;
  /**
   * Client
   */
  client?: string | null;
  /**
   * Device
   */
  device?: string | null;
};

/**
 * ApplySchedulingTemplateRequest
 */
export type ApplySchedulingTemplateRequest = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Template name
   */
  template_name: string;
  /**
   * Date
   */
  date: string;
  /**
   * Clear events
   *
   * Clear all events before applying the template
   */
  clear?: boolean;
};

/**
 * BasePlayoutChannelSettings
 */
export type BasePlayoutChannelSettings = {
  /**
   * ID
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Playout frame rate
   *
   * Frame rate used for scheduling and playout
   */
  fps?: number;
  /**
   * Playout plugins
   *
   * List of playout plugins used by the channele.g. for secondary events or graphic layers
   */
  plugins?: Array<string>;
  /**
   * Playout solvers
   *
   * List of rundown solver plugins enabled for the channel.
   */
  solvers?: Array<string>;
  /**
   * Day start time
   *
   * Time of day when the scheduling day starts, in hours and minutes.
   */
  day_start?: [number, number];
  /**
   * Rundown columns
   *
   * List of columns that are displayed in the rundown table
   */
  rundown_columns?: Array<string>;
  /**
   * Fields
   *
   * Metadata fields available for the channel events
   */
  fields?: Array<FolderField>;
  /**
   * Send to playout action
   *
   * ID of the action that is used to send media files to playout.
   */
  send_action?: number | null;
  /**
   * Scheduler accepts
   *
   * Criteria for accepting assets to be added to the channel scheduler.
   */
  scheduler_accepts?: AcceptModel;
  /**
   * Rundown accepts
   *
   * Criteria for accepting assets to be added to the channel rundown.
   */
  rundown_accepts?: AcceptModel;
  /**
   * Default template
   *
   * Name of the default template used to auto-populate the channel schedule.
   */
  default_template?: string | null;
};

/**
 * BaseSystemSettings
 *
 * Base system settings.
 *
 * Contains settings that are common for server and client.
 * Not all settings are used by the client.
 */
export type BaseSystemSettings = {
  /**
   * Site name
   *
   * A name used as the site (instance) identification
   */
  site_name?: string;
  /**
   * Default language
   */
  language?: 'en' | 'cs';
  /**
   * Create assets in UI
   *
   * Allow creating assets in the UI(when set to false, assets can only be created via API and watch folders)
   */
  ui_asset_create?: boolean;
  /**
   * Preview assets in UI
   *
   * Allow previewing low-res proxies of assets in the UI
   */
  ui_asset_preview?: boolean;
  /**
   * Upload assets in UI
   *
   * Allow uploading asset media files in the UI (when set to false, assets can  be uploaded via API and watch folders)
   */
  ui_asset_upload?: boolean;
  /**
   * Subtitle separator
   *
   * String used to separate title and subtitle in displayed title
   */
  subtitle_separator?: string;
};

/**
 * BrowseAssetsRequest
 */
export type BrowseAssetsRequest = {
  /**
   * View ID
   */
  view?: number | null;
  /**
   * Search query
   */
  query?: string | null;
  /**
   * Conditions
   *
   * List of additional conditions
   */
  conditions?: Array<ConditionModel> | null;
  /**
   * Columns
   *
   * Override the view columns.Note that several columns are always included.
   */
  columns?: Array<string> | null;
  /**
   * Ignore view conditions
   */
  ignore_view_conditions?: boolean;
  /**
   * Limit
   *
   * Maximum number of items
   */
  limit?: number;
  /**
   * Offset
   *
   * Offset
   */
  offset?: number;
  /**
   * Order by
   */
  order_by?: string;
  /**
   * Order direction
   */
  order_dir?: OrderDirection;
};

/**
 * BrowseAssetsResponse
 */
export type BrowseAssetsResponse = {
  /**
   * Columns
   */
  columns: Array<string>;
  /**
   * Data
   */
  data: Array<{
    [key: string]:
      | number
      | number
      | string
      | boolean
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
  }>;
  /**
   * Order by
   */
  order_by: string;
  /**
   * Order direction
   */
  order_dir: OrderDirection;
};

/**
 * ClientCSItemModel
 */
export type ClientCsItemModel = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Role
   */
  role?: 'hidden' | 'header' | 'label' | 'option' | null;
};

/**
 * ClientInfo
 */
export type ClientInfo = {
  /**
   * Ip
   */
  ip: string;
  /**
   * Languages
   */
  languages?: Array<string>;
  location?: LocationInfo | null;
  agent?: AgentInfo | null;
};

/**
 * ClientMetaTypeModel
 */
export type ClientMetaTypeModel = {
  /**
   * Namespace
   */
  ns?: string;
  /**
   * Type
   *
   * Type of the value
   */
  type?: string;
  /**
   * Title
   *
   * Title of the field
   */
  title: string;
  /**
   * Header
   *
   * Shortened title used as a column header
   */
  header?: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Classification scheme
   *
   * Classification scheme URN
   */
  cs?: string | null;
  /**
   * Mode
   *
   * Mode / widget of the field
   */
  mode?: string | null;
  /**
   * Format
   *
   * Format of the field
   */
  format?: string | null;
  /**
   * Order
   *
   * Order of values in lists
   */
  order?: string | null;
  /**
   * Filter
   *
   * Filter for values in lists
   */
  filter?: string | null;
  /**
   * Default value
   */
  default?: unknown | null;
};

/**
 * ClientSettingsModel
 *
 * Client settings.
 *
 * This model is returned by the server to the client in the
 * /api/init request along with the current user information.
 */
export type ClientSettingsModel = {
  system: BaseSystemSettings;
  /**
   * Folders
   */
  folders?: Array<FolderSettings>;
  /**
   * Views
   */
  views?: Array<ViewSettings>;
  /**
   * Users
   */
  users?: Array<UserInfo>;
  /**
   * Metatypes
   */
  metatypes?: {
    [key: string]: ClientMetaTypeModel;
  };
  /**
   * Cs
   */
  cs?: {
    [key: string]: {
      [key: string]: ClientCsItemModel;
    };
  };
  /**
   * Playout Channels
   */
  playout_channels?: Array<BasePlayoutChannelSettings>;
  /**
   * Filetypes
   */
  filetypes?: {
    [key: string]: ContentType;
  };
  /**
   * Server URL
   */
  server_url?: string | null;
};

/**
 * ConditionModel
 */
export type ConditionModel = {
  /**
   * Key
   */
  key: string;
  /**
   * Value
   */
  value?:
    | number
    | number
    | string
    | boolean
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
  operator?: ConditionOperator;
};

export type ConditionOperator =
  | '='
  | 'LIKE'
  | 'ILIKE'
  | 'IN'
  | 'NOT IN'
  | 'IS NULL'
  | 'IS NOT NULL'
  | '>'
  | '>='
  | '<'
  | '<=';

/**
 * ContentType
 */
export type ContentType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * DeleteObjectsRequest
 */
export type DeleteObjectsRequest = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Object IDs
   *
   * A list of object IDs to delete
   */
  ids: Array<number>;
};

/**
 * EventData
 */
export type EventData = {
  /**
   * Event ID
   *
   * Event ID. None for new events.
   */
  id?: number | null;
  /**
   * Start time
   */
  start: number;
  /**
   * Asset ID
   *
   * ID of the asset to be used as a primary asset for this event.
   */
  id_asset?: number | null;
  /**
   * Items
   */
  items?: Array<{
    [key: string]: number | string | number | Array<string> | boolean | null;
  }> | null;
  /**
   * Event metadata
   *
   * Metadata for the event.
   */
  meta?: {
    [key: string]: number | string | number | Array<string> | boolean | null;
  } | null;
};

/**
 * FolderField
 */
export type FolderField = {
  /**
   * Field name
   */
  name: string;
  /**
   * Section
   */
  section?: string | null;
  /**
   * Editor mode
   */
  mode?: string | null;
  /**
   * Value format
   */
  format?: string | null;
  /**
   * Enumerator order mode
   */
  order?: string | null;
  /**
   * Enumerator filter
   */
  filter?: string | null;
  /**
   * Links to other fields
   */
  links?: Array<{
    [key: string]: unknown;
  }> | null;
};

/**
 * FolderLink
 */
export type FolderLink = {
  /**
   * Name
   */
  name: string;
  /**
   * View
   */
  view: number;
  /**
   * Source Key
   */
  source_key: string;
  /**
   * Target Key
   */
  target_key: string;
};

/**
 * FolderSettings
 */
export type FolderSettings = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
  /**
   * Fields
   */
  fields?: Array<FolderField>;
  /**
   * Links
   */
  links?: Array<FolderLink>;
};

/**
 * GetAuxDataRequest
 */
export type GetAuxDataRequest = {
  /**
   * Key
   *
   * Key of the aux data to retrieve
   */
  key?: string | null;
  /**
   * Type of the object the aux data is attached to
   */
  object_type?: ObjectType;
  /**
   * Object Id
   *
   * ID of the object the aux data is attached to
   */
  object_id: number;
  /**
   * Can Fail
   *
   * Return null instead of a 404 error if  not found.
   */
  can_fail?: boolean;
};

/**
 * GetAvailableActionsRequest
 */
export type GetAvailableActionsRequest = {
  /**
   * Asset IDs
   *
   * List of asset IDs for which to get available actions
   */
  ids: Array<number>;
};

/**
 * GetAvailableActionsResponse
 */
export type GetAvailableActionsResponse = {
  /**
   * Actions
   *
   * List of available actions
   */
  actions?: Array<ActionItemModel>;
};

/**
 * GetObjectsRequest
 */
export type GetObjectsRequest = {
  /**
   * Object type
   *
   * Type of objects to get
   */
  object_type?: ObjectType;
  /**
   * Object IDs
   *
   * List of object IDs to retrieve
   */
  ids?: Array<number>;
};

/**
 * GetObjectsResponse
 */
export type GetObjectsResponse = {
  /**
   * Object data
   *
   * List of object data
   */
  data?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * GetTranscriptionRequest
 */
export type GetTranscriptionRequest = {
  /**
   * Id Asset
   *
   * Asset ID
   */
  id_asset: number;
};

/**
 * GetTranscriptionResponse
 */
export type GetTranscriptionResponse = {
  /**
   * Language
   *
   * Language of the transcription
   */
  language?: string | null;
  /**
   * Segments
   *
   * List of transcription segments
   */
  segments?: Array<TranscriptionSegment> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InvalidateSessionRequest
 */
export type InvalidateSessionRequest = {
  /**
   * Token
   */
  token: string;
};

export type ItemRole = 'lead_in' | 'lead_out' | 'placeholder' | 'live';

/**
 * JobListItem
 */
export type JobListItem = {
  /**
   * Job ID
   */
  id: number;
  /**
   * Job status
   */
  status: JobState;
  /**
   * Progress
   *
   * Progress of the job in percentage
   */
  progress: number;
  /**
   * Action ID
   *
   * ID of the action this job is running
   */
  id_action: number;
  /**
   * Service ID
   *
   * ID of the service this job is running on. Can be null if the job has not started yet
   */
  id_service?: number | null;
  /**
   * Asset ID
   *
   * ID of the asset this job is processing
   */
  id_asset: number;
  /**
   * User ID
   *
   * ID of the user who started the job
   */
  id_user?: number | null;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Status description
   *
   * Additional information about the job status
   */
  message?: string;
  /**
   * Created at
   *
   * Timestamp when the job was created
   */
  ctime?: number | null;
  /**
   * Started at
   *
   * Timestamp when the job was started. Can be null if the job has not started yet
   */
  stime?: number | null;
  /**
   * Ended at
   */
  etime?: number | null;
  /**
   * Asset name
   *
   * Asset full title (title + subtitle)
   */
  asset_name?: string | null;
  /**
   * Primary identifier
   */
  idec?: string | null;
  /**
   * Action Name
   */
  action_name?: string | null;
  /**
   * Service Name
   */
  service_name?: string | null;
  /**
   * Service Type
   */
  service_type?: string | null;
};

/**
 * JobState
 */
export type JobState = 0 | 1 | 2 | 3 | 4 | 5 | 6;

/**
 * ListSchedulingTemplatesResponse
 */
export type ListSchedulingTemplatesResponse = {
  /**
   * Templates
   */
  templates?: Array<SchedulingTemplateItemModel>;
};

/**
 * ListSessionsRequest
 */
export type ListSessionsRequest = {
  /**
   * Id User
   */
  id_user: number;
};

/**
 * ListUsersResponse
 *
 * Response model for listing users
 */
export type ListUsersResponse = {
  /**
   * List of users
   */
  users: Array<UserModel>;
};

/**
 * LocationInfo
 */
export type LocationInfo = {
  /**
   * Country
   */
  country?: string | null;
  /**
   * Subdivision
   */
  subdivision?: string | null;
  /**
   * City
   */
  city?: string | null;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   *
   * Password in plain text
   */
  password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
  /**
   * Access token
   *
   * Access token to be used in Authorization headerfor the subsequent requests
   */
  access_token: string;
};

/**
 * ManageJobsRequest
 */
export type ManageJobsRequest = {
  /**
   * View
   *
   * Defines, what jobs should be returned. When set to none, no jobs will be returned, but abort/restart/priority actions will still work
   */
  view?: 'all' | 'active' | 'finished' | 'failed' | null;
  /**
   * Job IDs
   *
   * Return only the jobs with the given IDs
   */
  ids?: Array<number> | null;
  /**
   * Asset IDs
   *
   * Return jobs of asset with the given IDs
   */
  asset_ids?: Array<number> | null;
  /**
   * Search query
   *
   * Search for jobs with given string in title
   */
  search_query?: string | null;
  /**
   * Abort
   *
   * Abort job with given id
   */
  abort?: number | null;
  /**
   * Restart
   *
   * Restart job with given id
   */
  restart?: number | null;
  /**
   * Priority
   *
   * Set priority of job with given id. First value is the job id, second is the priority
   */
  priority?: [number, number] | null;
};

/**
 * ManageJobsResponse
 */
export type ManageJobsResponse = {
  /**
   * Jobs
   */
  jobs?: Array<JobListItem> | null;
};

/**
 * ManageServicesRequest
 */
export type ManageServicesRequest = {
  /**
   * Stop ID
   *
   * ID of service to stop
   */
  stop?: number | null;
  /**
   * Start ID
   *
   * ID of service to start
   */
  start?: number | null;
  /**
   * Toggle autostart
   *
   * ID of service to toggle autostart
   */
  auto?: number | null;
};

/**
 * ManageServicesResponse
 */
export type ManageServicesResponse = {
  /**
   * Services
   */
  services?: Array<ServiceListItem>;
};

/**
 * MediaType
 */
export type MediaType = 0 | 1 | 2;

/**
 * NebulaStorageUsage
 */
export type NebulaStorageUsage = {
  /**
   * Label
   */
  label: string;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Usage
   */
  usage?: number;
  /**
   * Duration
   */
  duration?: number;
};

/**
 * NebulaStoragesUsage
 */
export type NebulaStoragesUsage = {
  /**
   * Storages
   */
  storages: Array<StorageStat>;
};

/**
 * ObjectStatus
 *
 * Object status enumeration.
 *
 * This enumeration is used to indicate the status of an object.
 * Objects can be in one of the following states:
 *
 * - OFFLINE: Object is in the database, but not available on the filesystem.
 * - ONLINE: Object is in the database and available on the filesystem.
 * - CREATING: Media file exists, but was changed recently, so its metadata
 * is being updated.
 * - TRASHED: Object has been marked as deleted, but is still available on
 * the filesystem. It will be deleted permanently after some time.
 * - ARCHIVED: Object has been marked as archived, but is still available on
 * the filesystem. It will be deleted permanently after some time.
 * - RESET: User has requested to reset the metadata of the object,
 * this triggers a re-scan of the media file metadata.
 * - CORRUPTED: Object is corrupted, and cannot be used.
 * - REMOTE: Object is not available on the filesystem, but is available one
 * a remote storage (typically a playout item which media file is on a
 * production storage, but it hasn't been copied to the playout storage yet).
 * - UNKNOWN: Object status is unknown.
 * - AIRED: Only for items. Item has been broadcasted.
 * - ONAIR: Only for items. Item is currently being broadcasted.
 * - RETRIEVING: Asset is marked for retrieval from a remote/archive storage.
 */
export type ObjectStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

/**
 * ObjectType
 */
export type ObjectType = 'asset' | 'item' | 'bin' | 'event' | 'user';

/**
 * Operation
 */
export type Operation = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Object ID
   *
   * ID of the object to modify. Keep empty to create a new object
   */
  id?: number | null;
  /**
   * Data
   *
   * Metadata to be set
   */
  data: {
    [key: string]: unknown;
  };
};

/**
 * OperationResult
 */
export type OperationResult = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Success
   *
   * True if the operation succeeded, false otherwise
   */
  success: boolean;
  /**
   * Error message
   *
   * Error message if the operation failed
   */
  error?: string | null;
  /**
   * Object ID
   */
  id?: number | null;
};

/**
 * OperationsRequest
 */
export type OperationsRequest = {
  /**
   * Operations
   *
   * List of operations to be executed
   */
  operations: Array<Operation>;
};

/**
 * OperationsResponse
 */
export type OperationsResponse = {
  /**
   * Operations
   */
  operations: Array<OperationResult>;
  /**
   * Success
   *
   * True if all operations succeeded
   */
  success: boolean;
};

export type OrderDirection = 'asc' | 'desc';

/**
 * OrderItem
 *
 * An item in the order request
 */
export type OrderItem = {
  /**
   * Object type
   */
  type: 'item' | 'asset';
  /**
   * ID
   *
   * The ID of the object (none for new items)
   */
  id?: number | null;
  /**
   * Object metadata
   */
  meta?: {
    [key: string]: unknown;
  };
};

/**
 * OrderRequest
 */
export type OrderRequest = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Bin ID
   */
  id_bin: number;
  /**
   * Order
   */
  order: Array<OrderItem>;
};

/**
 * OrderResponse
 */
export type OrderResponse = {
  /**
   * Affected bins
   *
   * List of bins affected by the order changeThis includes the bin where the order was applied and any other bins that had items moved to/from it.This allows the client to know which bins need to be refreshed after the order change.
   */
  affected_bins: Array<number>;
};

/**
 * PasswordResetCallbackRequest
 */
export type PasswordResetCallbackRequest = {
  /**
   * Password reset token
   *
   * The token from the password reset email. This token is used to verify the password
   */
  token: string;
  /**
   * New password
   *
   * The new password to set for the account.
   */
  password: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
  /**
   * Email
   *
   * The email address associated with the account to reset the password for
   */
  email: string;
};

/**
 * PlayoutAction
 */
export type PlayoutAction =
  | 'cue'
  | 'take'
  | 'abort'
  | 'freeze'
  | 'retake'
  | 'set'
  | 'plugin_list'
  | 'plugin_exec'
  | 'stat'
  | 'recover'
  | 'cue_forward'
  | 'cue_backward';

/**
 * PlayoutControlRequest
 */
export type PlayoutControlRequest = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Action
   *
   * Action to be executed on the playout service
   */
  action: PlayoutAction;
  /**
   * Payload
   *
   * Engine specific action arguments
   */
  payload?: {
    [key: string]: unknown;
  };
};

/**
 * PlayoutControlResponse
 */
export type PlayoutControlResponse = {
  /**
   * Plugins
   */
  plugins?: Array<PlayoutPluginManifest> | null;
};

/**
 * PlayoutPluginManifest
 */
export type PlayoutPluginManifest = {
  /**
   * Plugin name
   */
  name: string;
  /**
   * Plugin title
   */
  title: string;
  /**
   * Plugin slots
   *
   * List of plugin slots (inputs)
   */
  slots?: Array<PlayoutPluginSlot> | null;
};

/**
 * PlayoutPluginSlot
 */
export type PlayoutPluginSlot = {
  /**
   * Type
   */
  type: 'action' | 'text' | 'number' | 'select';
  /**
   * Name
   */
  name: string;
  /**
   * Options
   */
  options?: Array<PlayoutPluginSlotOption>;
  /**
   * Value
   */
  value?: unknown;
};

/**
 * PlayoutPluginSlotOption
 */
export type PlayoutPluginSlotOption = {
  /**
   * Value
   */
  value: string;
  /**
   * Title
   */
  title?: string | null;
};

/**
 * PluginItemModel
 *
 * Plugin item model.
 *
 * This model is used to describe a plugin in the frontend.
 */
export type PluginItemModel = {
  /**
   * Plugin name
   */
  name: string;
  /**
   * Plugin title
   */
  title: string;
  /**
   * Addon icon
   */
  icon?: string | null;
  /**
   * Plugin scope
   */
  scope?: 'tool' | 'mam';
  /**
   * Plugin directory
   */
  path: string;
};

/**
 * ProxyInfo
 */
export type ProxyInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Available
   */
  available: boolean;
  /**
   * Timestamp
   */
  timestamp: number | null;
};

/**
 * RunMode
 */
export type RunMode = 0 | 1 | 2 | 3 | 4;

/**
 * RundownRequest
 */
export type RundownRequest = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Date
   *
   * Date for which to load the rundown in YYYY-MM-DD format. If not provided, the current date is used.
   */
  date?: string | null;
};

/**
 * RundownResponse
 */
export type RundownResponse = {
  /**
   * Rundown rows
   */
  rows?: Array<RundownRow>;
  /**
   * Response detail message
   */
  detail?: string | null;
};

/**
 * RundownRow
 */
export type RundownRow = {
  /**
   * Id
   */
  id: number;
  /**
   * Row Number
   */
  row_number: number;
  /**
   * Type
   */
  type: 'item' | 'event';
  /**
   * Id Bin
   */
  id_bin: number;
  /**
   * Id Event
   */
  id_event: number;
  /**
   * Scheduled Time
   */
  scheduled_time: number;
  /**
   * Broadcast Time
   */
  broadcast_time: number;
  /**
   * Meta
   */
  meta?: {
    [key: string]: unknown;
  } | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Subtitle
   */
  subtitle?: string | null;
  /**
   * Note
   */
  note?: string | null;
  /**
   * Id Asset
   */
  id_asset?: number | null;
  /**
   * Id Folder
   */
  id_folder?: number | null;
  /**
   * Asset Mtime
   */
  asset_mtime?: number | null;
  status?: ObjectStatus | null;
  /**
   * Transfer Progress
   */
  transfer_progress?: number | null;
  /**
   * Duration
   */
  duration?: number;
  /**
   * Mark In
   */
  mark_in?: number | null;
  /**
   * Mark Out
   */
  mark_out?: number | null;
  /**
   * Loop
   */
  loop?: boolean | null;
  run_mode?: RunMode | null;
  item_role?: ItemRole | null;
  /**
   * Is Empty
   */
  is_empty?: boolean;
  /**
   * Is Primary
   */
  is_primary?: boolean;
};

/**
 * SSOOption
 */
export type SsoOption = {
  /**
   * Name
   */
  name: string;
  /**
   * Title
   */
  title: string;
};

/**
 * SaveTranscriptionRequest
 */
export type SaveTranscriptionRequest = {
  /**
   * Id Asset
   *
   * Asset ID
   */
  id_asset: number;
  /**
   * Segments
   *
   * List of transcription segments
   */
  segments: Array<TranscriptionSegment>;
};

/**
 * SchedulerRequest
 */
export type SchedulerRequest = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Date
   *
   * Date of the week start in YYYY-MM-DD format.If none. event data won't be returned.
   */
  date?: string | null;
  /**
   * Days
   *
   * Number of days to display. One week is the default
   */
  days?: number;
  /**
   * Delete events
   *
   * List of event IDs to delete
   */
  delete?: Array<number>;
  /**
   * Events
   *
   * List of events to create or update
   */
  events?: Array<EventData>;
};

/**
 * SchedulerResponse
 */
export type SchedulerResponse = {
  /**
   * Affected events
   *
   * List of event IDs that were affected by this request
   */
  affected_events?: Array<number>;
  /**
   * Affected bins
   *
   * List of bin IDs that were affected by this request
   */
  affected_bins?: Array<number>;
  /**
   * Events
   *
   * List of events
   */
  events?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * SchedulingTemplateItemModel
 */
export type SchedulingTemplateItemModel = {
  /**
   * Template name
   */
  name: string;
  /**
   * Template title
   */
  title: string;
};

/**
 * ScopedEndpoint
 */
export type ScopedEndpoint = {
  /**
   * Endpoint
   */
  endpoint: string;
  /**
   * Title
   */
  title: string;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * SendInvitationEmailRequest
 *
 * Request model for sending an invitation email to a user.
 */
export type SendInvitationEmailRequest = {
  /**
   * User ID
   */
  id: number;
};

/**
 * SendToRequest
 */
export type SendToRequest = {
  /**
   * Asset IDs
   *
   * List of asset ids
   */
  ids?: Array<number>;
  /**
   * Action ID
   *
   * Action ID
   */
  id_action: number;
  /**
   * Restart existing jobs
   */
  restart_existing?: boolean;
  /**
   * Restart running jobs
   */
  restart_running?: boolean;
  /**
   * Additional job parameters (action specific)
   */
  params?: {
    [key: string]: unknown;
  };
  /**
   * Job priority
   */
  priority?: number;
};

/**
 * SendToResponse
 */
export type SendToResponse = {
  /**
   * Job IDs
   *
   * List of job ids created/restarted.
   */
  ids?: Array<number | null>;
};

/**
 * ServerInfoResponse
 */
export type ServerInfoResponse = {
  /**
   * Installed
   *
   * Is Nebula installed?
   */
  installed?: boolean | null;
  /**
   * Message of the day
   *
   * Server welcome string (displayed on login page)
   */
  motd?: string | null;
  /**
   * Background
   *
   * Is the login background image enabled?
   */
  background?: boolean;
  /**
   * Current user
   *
   * User data if user is logged in
   */
  user?: UserModel | null;
  /**
   * Client settings
   */
  settings?: ClientSettingsModel | null;
  /**
   * Frontend plugins
   *
   * List of plugins available for the web frontend
   */
  frontend_plugins?: Array<PluginItemModel> | null;
  /**
   * Scoped endpoints
   *
   * List of available scoped endpoints
   */
  scoped_endpoints?: Array<ScopedEndpoint> | null;
  /**
   * SSO options
   */
  sso_options?: Array<SsoOption> | null;
  /**
   * Enable experimental features
   */
  experimental?: boolean | null;
};

/**
 * ServiceListItem
 */
export type ServiceListItem = {
  /**
   * Service ID
   */
  id: number;
  /**
   * Service name
   */
  name: string;
  /**
   * Service type
   */
  type: string;
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Service status
   *
   * Current status of the service
   */
  status: ServiceState;
  /**
   * Autostart
   */
  autostart: boolean;
  /**
   * Last seen
   *
   * Number of seconds since service was last seen
   */
  last_seen: number;
};

/**
 * ServiceState
 */
export type ServiceState = 0 | 1 | 2 | 3 | 4;

/**
 * SessionModel
 */
export type SessionModel = {
  /**
   * User
   *
   * User data
   */
  user: {
    [key: string]: unknown;
  };
  /**
   * Token
   *
   * Access token
   */
  token: string;
  /**
   * Created
   *
   * Creation timestamp
   */
  created: number;
  /**
   * Accessed
   *
   * Last access timestamp
   */
  accessed: number;
  /**
   * Client info
   */
  client_info?: ClientInfo | null;
  /**
   * Transient
   */
  transient?: boolean;
};

/**
 * SetPasswordRequest
 */
export type SetPasswordRequest = {
  /**
   * Login
   */
  login?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * SolveRequest
 */
export type SolveRequest = {
  /**
   * Solver
   */
  solver: string;
  /**
   * Items
   *
   * List of placeholder item IDs to solve
   */
  items: Array<number>;
};

/**
 * StorageStat
 */
export type StorageStat = {
  /**
   * Storage Id
   */
  storage_id: number;
  /**
   * Label
   */
  label: string;
  /**
   * Total
   */
  total: number;
  /**
   * Used
   */
  used: number;
  /**
   * Free
   */
  free: number;
  /**
   * Untracked
   */
  untracked: number;
  /**
   * Available
   */
  available?: boolean;
  /**
   * Nebula Usage
   */
  nebula_usage: Array<NebulaStorageUsage>;
  /**
   * Enabled
   */
  enabled?: boolean;
};

/**
 * TokenExchangeRequest
 */
export type TokenExchangeRequest = {
  /**
   * Access token
   *
   * Access token to be exchanged for a new one
   */
  access_token: string;
};

/**
 * TranscriptionSegment
 */
export type TranscriptionSegment = {
  /**
   * Start
   */
  start: number;
  /**
   * End
   */
  end: number;
  /**
   * Text
   */
  text: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Full Name
   */
  full_name?: string | null;
};

/**
 * UserModel
 */
export type UserModel = {
  /**
   * Id
   */
  id?: number | null;
  /**
   * Login
   */
  login: string;
  /**
   * Ctime
   */
  ctime?: number;
  /**
   * Mtime
   */
  mtime?: number;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Local Network Only
   */
  local_network_only?: boolean;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Is Limited
   */
  is_limited?: boolean;
  permissions?: UserPermissionsModel;
  /**
   * Password
   */
  password?: string | null;
  /**
   * Api Key
   */
  api_key?: string | null;
};

/**
 * UserPermissionsModel
 *
 * User permission model.
 */
export type UserPermissionsModel = {
  /**
   * Can view assets
   *
   * List of folder IDs user can view. Use 'true' for all folders
   */
  asset_view?: boolean | Array<number>;
  /**
   * Can asset edit
   *
   * List of folder IDs user can edit. Use 'true' for all folders
   */
  asset_edit?: boolean | Array<number>;
  /**
   * Can view rundown
   *
   * List of channel IDs user can view. 'true' for all channels
   */
  rundown_view?: boolean | Array<number>;
  /**
   * Can edit rundown
   *
   * List of channel IDs user can edit. 'true' for all channels
   */
  rundown_edit?: boolean | Array<number>;
  /**
   * Can view scheduler
   *
   * List of channel IDs user can view. 'true' for all channels
   */
  scheduler_view?: boolean | Array<number>;
  /**
   * Can edit scheduler
   *
   * List of channel IDs user can edit. 'true' for all channels
   */
  scheduler_edit?: boolean | Array<number>;
  /**
   * Can control services
   *
   * List of service IDs user can control
   */
  service_control?: boolean | Array<number>;
  /**
   * Can control playout
   *
   * List of channel IDs user can control
   */
  mcr?: boolean | Array<number>;
  /**
   * Can control jobs
   *
   * Use list of action IDs to grant access to specific actions
   */
  job_control?: boolean | Array<number>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * ViewSettings
 */
export type ViewSettings = {
  /**
   * ID
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Position
   */
  position: number;
  /**
   * Folders
   */
  folders?: Array<number> | null;
  /**
   * States
   */
  states?: Array<number> | null;
  /**
   * Columns
   */
  columns?: Array<string> | null;
  /**
   * Conditions
   */
  conditions?: Array<string> | null;
  /**
   * Separator
   */
  separator?: boolean;
};

export type LoginBackgroundApiLoginBackgroundJpgGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/login-background.jpg';
};

export type LoginBackgroundApiLoginBackgroundJpgGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type StatsStoragesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/stats/storages';
};

export type StatsStoragesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StatsStoragesError = StatsStoragesErrors[keyof StatsStoragesErrors];

export type StatsStoragesResponses = {
  /**
   * Successful Response
   */
  200: NebulaStoragesUsage;
};

export type StatsStoragesResponse =
  StatsStoragesResponses[keyof StatsStoragesResponses];

export type RundownData = {
  body: RundownRequest;
  path?: never;
  query?: never;
  url: '/api/rundown';
};

export type RundownErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RundownError = RundownErrors[keyof RundownErrors];

export type RundownResponses = {
  /**
   * Successful Response
   */
  200: RundownResponse;
};

export type RundownResponse2 = RundownResponses[keyof RundownResponses];

export type ServicesData = {
  body: ManageServicesRequest;
  path?: never;
  query?: never;
  url: '/api/services';
};

export type ServicesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ServicesError = ServicesErrors[keyof ServicesErrors];

export type ServicesResponses = {
  /**
   * Successful Response
   */
  200: ManageServicesResponse;
};

export type ServicesResponse = ServicesResponses[keyof ServicesResponses];

export type GetTranscriptionData = {
  body: GetTranscriptionRequest;
  path?: never;
  query?: never;
  url: '/api/get_transcription';
};

export type GetTranscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTranscriptionError =
  GetTranscriptionErrors[keyof GetTranscriptionErrors];

export type GetTranscriptionResponses = {
  /**
   * Successful Response
   */
  200: GetTranscriptionResponse;
};

export type GetTranscriptionResponse2 =
  GetTranscriptionResponses[keyof GetTranscriptionResponses];

export type SaveTranscriptionData = {
  body: SaveTranscriptionRequest;
  path?: never;
  query?: never;
  url: '/api/save_transcription';
};

export type SaveTranscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveTranscriptionError =
  SaveTranscriptionErrors[keyof SaveTranscriptionErrors];

export type SaveTranscriptionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type BrowseData = {
  body: BrowseAssetsRequest;
  path?: never;
  query?: never;
  url: '/api/browse';
};

export type BrowseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BrowseError = BrowseErrors[keyof BrowseErrors];

export type BrowseResponses = {
  /**
   * Successful Response
   */
  200: BrowseAssetsResponse;
};

export type BrowseResponse = BrowseResponses[keyof BrowseResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/list-users';
};

export type ListUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
  /**
   * Successful Response
   */
  200: ListUsersResponse;
};

export type ListUsersResponse2 = ListUsersResponses[keyof ListUsersResponses];

export type SaveUserData = {
  body: UserModel;
  path?: never;
  query?: never;
  url: '/api/save-user';
};

export type SaveUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveUserError = SaveUserErrors[keyof SaveUserErrors];

export type SaveUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SendInvitationEmailData = {
  body: SendInvitationEmailRequest;
  path?: never;
  query?: never;
  url: '/api/send-invitation-email';
};

export type SendInvitationEmailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendInvitationEmailError =
  SendInvitationEmailErrors[keyof SendInvitationEmailErrors];

export type SendInvitationEmailResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteData = {
  body: DeleteObjectsRequest;
  path?: never;
  query?: never;
  url: '/api/delete';
};

export type DeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAuxData = {
  body: GetAuxDataRequest;
  path?: never;
  query?: never;
  url: '/api/get-aux';
};

export type GetAuxErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAuxError = GetAuxErrors[keyof GetAuxErrors];

export type GetAuxResponses = {
  /**
   * Response Get Aux
   *
   * Successful Response
   */
  200: unknown;
};

export type GetData = {
  body: GetObjectsRequest;
  path?: never;
  query?: never;
  url: '/api/get';
};

export type GetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
  /**
   * Successful Response
   */
  200: GetObjectsResponse;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type OpsData = {
  body: OperationsRequest;
  path?: never;
  query?: never;
  url: '/api/ops';
};

export type OpsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpsError = OpsErrors[keyof OpsErrors];

export type OpsResponses = {
  /**
   * Successful Response
   */
  200: OperationsResponse;
};

export type OpsResponse = OpsResponses[keyof OpsResponses];

export type SetData = {
  body: Operation;
  path?: never;
  query?: never;
  url: '/api/set';
};

export type SetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetError = SetErrors[keyof SetErrors];

export type SetResponses = {
  /**
   * Successful Response
   */
  200: OperationResult;
};

export type SetResponse = SetResponses[keyof SetResponses];

export type OrderData = {
  body: OrderRequest;
  path?: never;
  query?: never;
  url: '/api/order';
};

export type OrderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OrderError = OrderErrors[keyof OrderErrors];

export type OrderResponses = {
  /**
   * Successful Response
   */
  200: OrderResponse;
};

export type OrderResponse2 = OrderResponses[keyof OrderResponses];

export type SolveData = {
  body: SolveRequest;
  path?: never;
  query?: never;
  url: '/api/solve';
};

export type SolveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SolveError = SolveErrors[keyof SolveErrors];

export type SolveResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ApplySchedulingTemplateData = {
  body: ApplySchedulingTemplateRequest;
  path?: never;
  query?: never;
  url: '/api/apply-scheduling-template';
};

export type ApplySchedulingTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApplySchedulingTemplateError =
  ApplySchedulingTemplateErrors[keyof ApplySchedulingTemplateErrors];

export type ApplySchedulingTemplateResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListSchedulingTemplatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/list-scheduling-templates';
};

export type ListSchedulingTemplatesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSchedulingTemplatesError =
  ListSchedulingTemplatesErrors[keyof ListSchedulingTemplatesErrors];

export type ListSchedulingTemplatesResponses = {
  /**
   * Successful Response
   */
  200: ListSchedulingTemplatesResponse;
};

export type ListSchedulingTemplatesResponse2 =
  ListSchedulingTemplatesResponses[keyof ListSchedulingTemplatesResponses];

export type PlayoutData = {
  body: PlayoutControlRequest;
  path?: never;
  query?: never;
  url: '/api/playout';
};

export type PlayoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PlayoutError = PlayoutErrors[keyof PlayoutErrors];

export type PlayoutResponses = {
  /**
   * Successful Response
   */
  200: PlayoutControlResponse;
};

export type PlayoutResponse = PlayoutResponses[keyof PlayoutResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/login';
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: '/api/logout';
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PasswordResetData = {
  body: PasswordResetRequest;
  path?: never;
  query?: never;
  url: '/api/password-reset';
};

export type PasswordResetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PasswordResetError = PasswordResetErrors[keyof PasswordResetErrors];

export type PasswordResetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PasswordResetCallbackData = {
  body: PasswordResetCallbackRequest;
  path?: never;
  query?: never;
  url: '/api/password-reset-callback';
};

export type PasswordResetCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PasswordResetCallbackError =
  PasswordResetCallbackErrors[keyof PasswordResetCallbackErrors];

export type PasswordResetCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SsoLoginData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: never;
  url: '/api/sso/login/{provider}';
};

export type SsoLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SsoLoginError = SsoLoginErrors[keyof SsoLoginErrors];

export type SsoLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SsoCallbackData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: never;
  url: '/api/sso/callback/{provider}';
};

export type SsoCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SsoCallbackError = SsoCallbackErrors[keyof SsoCallbackErrors];

export type SsoCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PasswordData = {
  body: SetPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/password';
};

export type PasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PasswordError = PasswordErrors[keyof PasswordErrors];

export type PasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TokenExchangeData = {
  body: TokenExchangeRequest;
  path?: never;
  query?: never;
  url: '/api/token-exchange';
};

export type TokenExchangeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TokenExchangeError = TokenExchangeErrors[keyof TokenExchangeErrors];

export type TokenExchangeResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type TokenExchangeResponse =
  TokenExchangeResponses[keyof TokenExchangeResponses];

export type InitData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/init';
};

export type InitErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InitError = InitErrors[keyof InitErrors];

export type InitResponses = {
  /**
   * Successful Response
   */
  200: ServerInfoResponse;
};

export type InitResponse = InitResponses[keyof InitResponses];

export type SchedulerData = {
  body: SchedulerRequest;
  path?: never;
  query?: never;
  url: '/api/scheduler';
};

export type SchedulerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SchedulerError = SchedulerErrors[keyof SchedulerErrors];

export type SchedulerResponses = {
  /**
   * Successful Response
   */
  200: SchedulerResponse;
};

export type SchedulerResponse2 = SchedulerResponses[keyof SchedulerResponses];

export type GetProxyInfoData = {
  body?: never;
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: never;
  url: '/proxy/{id_asset}/info';
};

export type GetProxyInfoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProxyInfoError = GetProxyInfoErrors[keyof GetProxyInfoErrors];

export type GetProxyInfoResponses = {
  /**
   * Successful Response
   */
  200: ProxyInfo;
};

export type GetProxyInfoResponse = GetProxyInfoResponses[keyof GetProxyInfoResponses];

export type ProxyData = {
  body?: never;
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: never;
  url: '/proxy/{id_asset}';
};

export type ProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyError = ProxyErrors[keyof ProxyErrors];

export type ProxyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UploadData = {
  body?: never;
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: never;
  url: '/upload/{id_asset}';
};

export type UploadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadError = UploadErrors[keyof UploadErrors];

export type UploadResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type InvalidateSessionData = {
  body: InvalidateSessionRequest;
  path?: never;
  query?: never;
  url: '/api/invalidate-session';
};

export type InvalidateSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InvalidateSessionError =
  InvalidateSessionErrors[keyof InvalidateSessionErrors];

export type InvalidateSessionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListSessionsData = {
  body: ListSessionsRequest;
  path?: never;
  query?: never;
  url: '/api/list-sessions';
};

export type ListSessionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
  /**
   * Response List Sessions
   *
   * Successful Response
   */
  200: Array<SessionModel>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type ActionsData = {
  body: GetAvailableActionsRequest;
  path?: never;
  query?: never;
  url: '/api/actions';
};

export type ActionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ActionsError = ActionsErrors[keyof ActionsErrors];

export type ActionsResponses = {
  /**
   * Successful Response
   */
  200: GetAvailableActionsResponse;
};

export type ActionsResponse = ActionsResponses[keyof ActionsResponses];

export type JobsData = {
  body: ManageJobsRequest;
  path?: never;
  query?: never;
  url: '/api/jobs';
};

export type JobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type JobsError = JobsErrors[keyof JobsErrors];

export type JobsResponses = {
  /**
   * Successful Response
   */
  200: ManageJobsResponse;
};

export type JobsResponse = JobsResponses[keyof JobsResponses];

export type SendData = {
  body: SendToRequest;
  path?: never;
  query?: never;
  url: '/api/send';
};

export type SendErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendError = SendErrors[keyof SendErrors];

export type SendResponses = {
  /**
   * Successful Response
   */
  200: SendToResponse;
};

export type SendResponse = SendResponses[keyof SendResponses];
