// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://a11.nbla.cloud' | (string & {});
};

/**
 * AcceptModel
 */
export type AcceptModel = {
  /**
   * Folders
   *
   * List of folder IDs
   */
  folders?: Array<number> | null;
  /**
   * Content types
   *
   * List of content types that are accepted. None means all types are accepted.
   */
  content_types?: Array<ContentType> | null;
  /**
   * Media types
   *
   * List of media types that are accepted. None means all types are accepted.
   */
  media_types?: Array<MediaType> | null;
};

/**
 * ActionItemModel
 */
export type ActionItemModel = {
  /**
   * Action ID
   */
  id: number;
  /**
   * Action name
   */
  name: string;
};

/**
 * ActionsRequestModel
 */
export type ActionsRequestModel = {
  /**
   * Asset IDs
   *
   * List of asset IDs for which to get available actions
   */
  ids: Array<number>;
};

/**
 * ActionsResponseModel
 */
export type ActionsResponseModel = {
  /**
   * Actions
   *
   * List of available actions
   */
  actions?: Array<ActionItemModel>;
};

/**
 * AgentInfo
 */
export type AgentInfo = {
  /**
   * Platform
   */
  platform?: string | null;
  /**
   * Client
   */
  client?: string | null;
  /**
   * Device
   */
  device?: string | null;
};

/**
 * ApplyTemplateRequestModel
 */
export type ApplyTemplateRequestModel = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Template name
   */
  template_name: string;
  /**
   * Date
   */
  date: string;
  /**
   * Clear events
   *
   * Clear all events before applying the template
   */
  clear?: boolean;
};

/**
 * AsrunXlsRequest
 */
export type AsrunXlsRequest = {
  /**
   * Idecs
   */
  idecs: Array<string>;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
};

/**
 * BasePlayoutChannelSettings
 */
export type BasePlayoutChannelSettings = {
  /**
   * ID
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Fps
   */
  fps?: number;
  /**
   * Plugins
   */
  plugins?: Array<string>;
  /**
   * Solvers
   */
  solvers?: Array<string>;
  /**
   * Day Start
   */
  day_start?: [number, number];
  /**
   * Rundown Columns
   */
  rundown_columns?: Array<string>;
  /**
   * Fields
   *
   * Metadata fields available for the channel events
   */
  fields?: Array<FolderField>;
  /**
   * Send Action
   */
  send_action?: number | null;
  scheduler_accepts?: AcceptModel;
  rundown_accepts?: AcceptModel;
  /**
   * Default Template
   */
  default_template?: string | null;
};

/**
 * BaseSystemSettings
 *
 * Base system settings.
 *
 * Contains settings that are common for server and client.
 * Not all settings are used by the client.
 */
export type BaseSystemSettings = {
  /**
   * Site name
   *
   * A name used as the site (instance) identification
   */
  site_name?: string;
  /**
   * Default language
   */
  language?: 'en' | 'cs';
  /**
   * Create assets in UI
   *
   * Allow creating assets in the UI(when set to false, assets can only be created via API and watch folders)
   */
  ui_asset_create?: boolean;
  /**
   * Preview assets in UI
   *
   * Allow previewing low-res proxies of assets in the UI
   */
  ui_asset_preview?: boolean;
  /**
   * Upload assets in UI
   *
   * Allow uploading asset media files in the UI (when set to false, assets can only be uploaded via API and watch folders)
   */
  ui_asset_upload?: boolean;
  /**
   * Subtitle separator
   *
   * String used to separate title and subtitle in displayed title
   */
  subtitle_separator?: string;
};

/**
 * BrowseRequestModel
 */
export type BrowseRequestModel = {
  /**
   * View ID
   */
  view?: number | null;
  /**
   * Search query
   */
  query?: string | null;
  /**
   * Conditions
   *
   * List of additional conditions
   */
  conditions?: Array<ConditionModel> | null;
  /**
   * Columns
   *
   * Override the view columns.Note that several columns are always included.
   */
  columns?: Array<string> | null;
  /**
   * Ignore view conditions
   */
  ignore_view_conditions?: boolean;
  /**
   * Limit
   *
   * Maximum number of items
   */
  limit?: number;
  /**
   * Offset
   *
   * Offset
   */
  offset?: number;
  /**
   * Order by
   */
  order_by?: string;
  /**
   * Order direction
   */
  order_dir?: 'asc' | 'desc';
};

/**
 * BrowseResponseModel
 */
export type BrowseResponseModel = {
  /**
   * Columns
   */
  columns: Array<string>;
  /**
   * Data
   */
  data: Array<{
    [key: string]:
      | number
      | number
      | string
      | boolean
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
  }>;
  /**
   * Order by
   */
  order_by: string;
  /**
   * Order direction
   */
  order_dir: 'asc' | 'desc';
};

/**
 * ClientCSItemModel
 */
export type ClientCsItemModel = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Role
   */
  role?: 'hidden' | 'header' | 'label' | 'option' | null;
};

/**
 * ClientInfo
 */
export type ClientInfo = {
  /**
   * Ip
   */
  ip: string;
  /**
   * Languages
   */
  languages?: Array<string>;
  location?: LocationInfo | null;
  agent?: AgentInfo | null;
};

/**
 * ClientMetaTypeModel
 */
export type ClientMetaTypeModel = {
  /**
   * Namespace
   */
  ns?: string;
  /**
   * Type
   *
   * Type of the value
   */
  type?: string;
  /**
   * Title
   *
   * Title of the field
   */
  title: string;
  /**
   * Header
   *
   * Shortened title used as a column header
   */
  header?: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Classification scheme
   *
   * Classification scheme URN
   */
  cs?: string | null;
  /**
   * Mode
   *
   * Mode / widget of the field
   */
  mode?: string | null;
  /**
   * Format
   *
   * Format of the field
   */
  format?: string | null;
  /**
   * Order
   *
   * Order of values in lists
   */
  order?: string | null;
  /**
   * Filter
   *
   * Filter for values in lists
   */
  filter?: string | null;
  /**
   * Default value
   */
  default?: unknown | null;
};

/**
 * ClientSettingsModel
 *
 * Client settings.
 *
 * This model is returned by the server to the client in the
 * /api/init request along with the current user information.
 */
export type ClientSettingsModel = {
  system?: BaseSystemSettings;
  /**
   * Folders
   */
  folders?: Array<FolderSettings>;
  /**
   * Views
   */
  views?: Array<ViewSettings>;
  /**
   * Users
   */
  users?: Array<UserInfo>;
  /**
   * Metatypes
   */
  metatypes?: {
    [key: string]: ClientMetaTypeModel;
  };
  /**
   * Cs
   */
  cs?: {
    [key: string]: {
      [key: string]: ClientCsItemModel;
    };
  };
  /**
   * Playout Channels
   */
  playout_channels?: Array<BasePlayoutChannelSettings>;
  /**
   * Filetypes
   */
  filetypes?: {
    [key: string]: ContentType;
  };
  /**
   * Server URL
   */
  server_url?: string | null;
};

/**
 * ConditionModel
 */
export type ConditionModel = {
  /**
   * Key
   */
  key: string;
  /**
   * Value
   */
  value?:
    | number
    | number
    | string
    | boolean
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
  /**
   * Operator
   */
  operator?:
    | '='
    | 'LIKE'
    | 'ILIKE'
    | 'IN'
    | 'NOT IN'
    | 'IS NULL'
    | 'IS NOT NULL'
    | '>'
    | '>='
    | '<'
    | '<=';
};

/**
 * ContentType
 */
export type ContentType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * ContextPluginResponseModel
 */
export type ContextPluginResponseModel = {
  /**
   * Type
   */
  type?: string;
  /**
   * Header
   */
  header?: string | null;
  /**
   * Footer
   */
  footer?: string | null;
  /**
   * Dialog Style
   */
  dialog_style?: {
    [key: string]: unknown;
  };
  /**
   * Payload
   */
  payload?: {
    [key: string]: unknown;
  };
};

/**
 * ContextTestRequest
 */
export type ContextTestRequest = {
  /**
   * Id Asset
   *
   * Asset ID
   */
  id_asset: number;
};

/**
 * DeleteRequestModel
 */
export type DeleteRequestModel = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Object IDs
   *
   * A list of object IDs to delete
   */
  ids: Array<number>;
};

/**
 * EventData
 */
export type EventData = {
  /**
   * Event ID
   *
   * Event ID. None for new events.
   */
  id?: number | null;
  /**
   * Start time
   */
  start: number;
  /**
   * Asset ID
   *
   * ID of the asset to be used as a primary asset for this event.
   */
  id_asset?: number | null;
  /**
   * Items
   */
  items?: Array<{
    [key: string]: number | string | number | Array<string> | boolean | null;
  }> | null;
  /**
   * Event metadata
   *
   * Metadata for the event.
   */
  meta?: {
    [key: string]: number | string | number | Array<string> | boolean | null;
  } | null;
};

/**
 * FolderField
 */
export type FolderField = {
  /**
   * Field name
   */
  name: string;
  /**
   * Section
   */
  section?: string | null;
  /**
   * Mode
   */
  mode?: string | null;
  /**
   * Format
   */
  format?: string | null;
  /**
   * Order
   */
  order?: string | null;
  /**
   * Filter
   */
  filter?: string | null;
  /**
   * Links
   */
  links?: Array<unknown>;
};

/**
 * FolderLink
 */
export type FolderLink = {
  /**
   * Name
   */
  name: string;
  /**
   * View
   */
  view: number;
  /**
   * Source Key
   */
  source_key: string;
  /**
   * Target Key
   */
  target_key: string;
};

/**
 * FolderSettings
 */
export type FolderSettings = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
  /**
   * Fields
   */
  fields?: Array<FolderField>;
  /**
   * Links
   */
  links?: Array<FolderLink>;
};

/**
 * GetRequestModel
 */
export type GetRequestModel = {
  /**
   * Object type
   *
   * Type of objects to get
   */
  object_type?: ObjectType;
  /**
   * Object IDs
   *
   * List of object IDs to retrieve
   */
  ids?: Array<number>;
};

/**
 * GetResponseModel
 */
export type GetResponseModel = {
  /**
   * Object data
   *
   * List of object data
   */
  data?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InitResponseModel
 */
export type InitResponseModel = {
  /**
   * Installed
   *
   * Is Nebula installed?
   */
  installed?: boolean | null;
  /**
   * Message of the day
   *
   * Server welcome string (displayed on login page)
   */
  motd?: string | null;
  /**
   * Background
   *
   * Is the login background image enabled?
   */
  background?: boolean;
  /**
   * Current user
   *
   * User data if user is logged in
   */
  user?: UserModel | null;
  /**
   * Client settings
   */
  settings?: ClientSettingsModel | null;
  /**
   * Frontend plugins
   *
   * List of plugins available for the web frontend
   */
  frontend_plugins?: Array<PluginItemModel> | null;
  /**
   * Scoped endpoints
   *
   * List of available scoped endpoints
   */
  scoped_endpoints?: Array<ScopedEndpoint> | null;
  /**
   * SSO options
   */
  sso_options?: Array<SsoOption> | null;
  /**
   * Enable experimental features
   */
  experimental?: boolean | null;
};

/**
 * InvalidateSessionRequestModel
 */
export type InvalidateSessionRequestModel = {
  /**
   * Token
   */
  token: string;
};

/**
 * JobState
 */
export type JobState = 0 | 1 | 2 | 3 | 4 | 5 | 6;

/**
 * JobsItemModel
 */
export type JobsItemModel = {
  /**
   * Job ID
   */
  id: number;
  /**
   * Job status
   */
  status: JobState;
  /**
   * Progress
   */
  progress: number;
  /**
   * Action ID
   */
  id_action: number;
  /**
   * Service ID
   */
  id_service?: number | null;
  /**
   * Asset ID
   */
  id_asset: number;
  /**
   * User ID
   *
   * ID of the user who started the job
   */
  id_user?: number | null;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Status description
   */
  message: string;
  /**
   * Created at
   */
  ctime?: number | null;
  /**
   * Started at
   */
  stime?: number | null;
  /**
   * Finished at
   */
  etime?: number | null;
  /**
   * Asset name
   *
   * Asset full title (title + subtitle)
   */
  asset_name?: string | null;
  /**
   * Primary identifier
   */
  idec?: string | null;
  /**
   * Action Name
   */
  action_name?: string | null;
  /**
   * Service Name
   */
  service_name?: string | null;
  /**
   * Service Type
   */
  service_type?: string | null;
};

/**
 * JobsRequestModel
 */
export type JobsRequestModel = {
  /**
   * View
   *
   * Defines, what jobs should be returned.
   * When set to none, 204 response is returned instead of list of jobs
   */
  view?: 'all' | 'active' | 'finished' | 'failed' | null;
  /**
   * Job IDs
   *
   * Return only the jobs with the given IDs
   */
  ids?: Array<number> | null;
  /**
   * Asset IDs
   *
   * Return jobs of asset with the given IDs
   */
  asset_ids?: Array<number> | null;
  /**
   * Search query
   *
   * Search for jobs with given string in title
   */
  search_query?: string | null;
  /**
   * Abort
   *
   * Abort job with given id
   */
  abort?: number | null;
  /**
   * Restart
   *
   * Restart job with given id
   */
  restart?: number | null;
  /**
   * Priority
   *
   * Set priority of job with given id. First value is the job id, second is the priority
   */
  priority?: [number, number] | null;
};

/**
 * JobsResponseModel
 */
export type JobsResponseModel = {
  /**
   * Jobs
   */
  jobs?: Array<JobsItemModel> | null;
};

/**
 * ListSessionsRequestModel
 */
export type ListSessionsRequestModel = {
  /**
   * Id User
   */
  id_user: number;
};

/**
 * ListTemplatesResponseModel
 */
export type ListTemplatesResponseModel = {
  /**
   * Templates
   */
  templates?: Array<TemplateItemModel>;
};

/**
 * ListUsersResponseModel
 *
 * Response model for listing users
 */
export type ListUsersResponseModel = {
  /**
   * List of users
   */
  users: Array<UserModel>;
};

/**
 * LocationInfo
 */
export type LocationInfo = {
  /**
   * Country
   */
  country?: string | null;
  /**
   * Subdivision
   */
  subdivision?: string | null;
  /**
   * City
   */
  city?: string | null;
};

/**
 * LoginRequestModel
 */
export type LoginRequestModel = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   *
   * Password in plain text
   */
  password: string;
};

/**
 * LoginResponseModel
 */
export type LoginResponseModel = {
  /**
   * Access token
   *
   * Access token to be used in Authorization headerfor the subsequent requests
   */
  access_token: string;
};

/**
 * MediaType
 */
export type MediaType = 0 | 1 | 2;

/**
 * NebulaStorageUsage
 */
export type NebulaStorageUsage = {
  /**
   * Label
   */
  label: string;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Usage
   */
  usage?: number;
  /**
   * Duration
   */
  duration?: number;
};

/**
 * NebulaStoragesUsage
 */
export type NebulaStoragesUsage = {
  /**
   * Storages
   */
  storages: Array<StorageStat>;
};

/**
 * ObjectStatus
 *
 * Object status enumeration.
 *
 * This enumeration is used to indicate the status of an object.
 * Objects can be in one of the following states:
 *
 * - OFFLINE: Object is in the database, but not available on the filesystem.
 * - ONLINE: Object is in the database and available on the filesystem.
 * - CREATING: Media file exists, but was changed recently, so its metadata
 * is being updated.
 * - TRASHED: Object has been marked as deleted, but is still available on
 * the filesystem. It will be deleted permanently after some time.
 * - ARCHIVED: Object has been marked as archived, but is still available on
 * the filesystem. It will be deleted permanently after some time.
 * - RESET: User has requested to reset the metadata of the object,
 * this triggers a re-scan of the media file metadata.
 * - CORRUPTED: Object is corrupted, and cannot be used.
 * - REMOTE: Object is not available on the filesystem, but is available one
 * a remote storage (typically a playout item which media file is on a
 * production storage, but it hasn't been copied to the playout storage yet).
 * - UNKNOWN: Object status is unknown.
 * - AIRED: Only for items. Item has been broadcasted.
 * - ONAIR: Only for items. Item is currently being broadcasted.
 * - RETRIEVING: Asset is marked for retrieval from a remote/archive storage.
 */
export type ObjectStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

/**
 * ObjectType
 */
export type ObjectType = 'asset' | 'item' | 'bin' | 'event' | 'user';

/**
 * OperationModel
 */
export type OperationModel = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Id
   *
   * Object ID. Keep empty to create a new object
   */
  id?: number | null;
  /**
   * Data
   *
   * Metadata to be set
   */
  data: {
    [key: string]: unknown;
  };
};

/**
 * OperationResponseModel
 */
export type OperationResponseModel = {
  /**
   * Object type
   */
  object_type?: ObjectType;
  /**
   * Success
   */
  success: boolean;
  /**
   * Error message
   */
  error?: string | null;
  /**
   * Object ID
   */
  id?: number | null;
};

/**
 * OperationsRequestModel
 */
export type OperationsRequestModel = {
  /**
   * Operations
   *
   * List of operations to be executed
   */
  operations: Array<OperationModel>;
};

/**
 * OperationsResponseModel
 */
export type OperationsResponseModel = {
  /**
   * Operations
   */
  operations: Array<OperationResponseModel>;
  /**
   * Success
   *
   * True if all operations succeeded
   */
  success: boolean;
};

/**
 * OrderItemModel
 *
 * An item in the order request
 */
export type OrderItemModel = {
  /**
   * ID
   *
   * The ID of the object (none for new items)
   */
  id?: number | null;
  /**
   * Object type
   */
  type: 'item' | 'asset';
  /**
   * Object metadata
   */
  meta?: {
    [key: string]: unknown;
  };
};

/**
 * OrderRequestModel
 */
export type OrderRequestModel = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Bin ID
   */
  id_bin: number;
  /**
   * Order
   */
  order: Array<OrderItemModel>;
};

/**
 * OrderResponseModel
 */
export type OrderResponseModel = {
  /**
   * Affected bins
   */
  affected_bins: Array<number>;
};

/**
 * PasswordRequestModel
 */
export type PasswordRequestModel = {
  /**
   * Login
   */
  login?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * PlayoutAction
 */
export type PlayoutAction =
  | 'cue'
  | 'take'
  | 'abort'
  | 'freeze'
  | 'retake'
  | 'set'
  | 'plugin_list'
  | 'plugin_exec'
  | 'stat'
  | 'recover'
  | 'cue_forward'
  | 'cue_backward';

/**
 * PlayoutPluginManifest
 */
export type PlayoutPluginManifest = {
  /**
   * Name
   */
  name: string;
  /**
   * Title
   */
  title: string;
  /**
   * Slots
   */
  slots?: Array<PlayoutPluginSlot> | null;
};

/**
 * PlayoutPluginSlot
 */
export type PlayoutPluginSlot = {
  /**
   * Type
   */
  type: 'action' | 'text' | 'number' | 'select';
  /**
   * Name
   */
  name: string;
  /**
   * Options
   */
  options?: Array<PlayoutPluginSlotOption>;
  /**
   * Value
   */
  value?: unknown;
};

/**
 * PlayoutPluginSlotOption
 */
export type PlayoutPluginSlotOption = {
  /**
   * Value
   */
  value: string;
  /**
   * Title
   */
  title?: string | null;
};

/**
 * PlayoutRequestModel
 */
export type PlayoutRequestModel = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Action
   *
   * Action to be executed on the playout service
   */
  action: PlayoutAction;
  /**
   * Payload
   *
   * Engine specific action arguments
   */
  payload?: {
    [key: string]: unknown;
  };
};

/**
 * PlayoutResponseModel
 */
export type PlayoutResponseModel = {
  /**
   * Plugins
   */
  plugins?: Array<PlayoutPluginManifest> | null;
};

/**
 * PluginItemModel
 *
 * Plugin item model.
 *
 * This model is used to describe a plugin in the frontend.
 */
export type PluginItemModel = {
  /**
   * Plugin name
   */
  name: string;
  /**
   * Plugin title
   */
  title: string;
  /**
   * Addon icon
   */
  icon?: string | null;
  /**
   * Plugin scope
   */
  scope?: 'tool' | 'mam';
  /**
   * Plugin directory
   */
  path: string;
};

/**
 * ProxyInfo
 */
export type ProxyInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Available
   */
  available: boolean;
  /**
   * Timestamp
   */
  timestamp: number | null;
};

/**
 * RunMode
 */
export type RunMode = 0 | 1 | 2 | 3 | 4;

/**
 * RundownRequestModel
 */
export type RundownRequestModel = {
  /**
   * Id Channel
   */
  id_channel: number;
  /**
   * Date
   */
  date?: string | null;
};

/**
 * RundownResponseModel
 */
export type RundownResponseModel = {
  /**
   * Rows
   */
  rows?: Array<RundownRow>;
  /**
   * Detail
   */
  detail?: string | null;
};

/**
 * RundownRow
 */
export type RundownRow = {
  /**
   * Id
   */
  id: number;
  /**
   * Row Number
   */
  row_number: number;
  /**
   * Type
   */
  type: 'item' | 'event';
  /**
   * Id Bin
   */
  id_bin: number;
  /**
   * Id Event
   */
  id_event: number;
  /**
   * Scheduled Time
   */
  scheduled_time: number;
  /**
   * Broadcast Time
   */
  broadcast_time: number;
  /**
   * Meta
   */
  meta?: {
    [key: string]: unknown;
  } | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Subtitle
   */
  subtitle?: string | null;
  /**
   * Note
   */
  note?: string | null;
  /**
   * Id Asset
   */
  id_asset?: number | null;
  /**
   * Id Folder
   */
  id_folder?: number | null;
  /**
   * Asset Mtime
   */
  asset_mtime?: number | null;
  status?: ObjectStatus | null;
  /**
   * Transfer Progress
   */
  transfer_progress?: number | null;
  /**
   * Duration
   */
  duration?: number;
  /**
   * Mark In
   */
  mark_in?: number | null;
  /**
   * Mark Out
   */
  mark_out?: number | null;
  run_mode?: RunMode | null;
  /**
   * Loop
   */
  loop?: boolean | null;
  /**
   * Item Role
   */
  item_role?: 'lead_in' | 'lead_out' | 'placeholder' | 'live' | null;
  /**
   * Is Empty
   */
  is_empty?: boolean;
  /**
   * Is Primary
   */
  is_primary?: boolean;
};

/**
 * SSOOption
 */
export type SsoOption = {
  /**
   * Name
   */
  name: string;
  /**
   * Title
   */
  title: string;
};

/**
 * SchedulerRequestModel
 */
export type SchedulerRequestModel = {
  /**
   * Channel ID
   */
  id_channel: number;
  /**
   * Date
   *
   * Date of the week start in YYYY-MM-DD format.If none. event data won't be returned.
   */
  date?: string | null;
  /**
   * Days
   *
   * Number of days to display. One week is the default
   */
  days?: number;
  /**
   * Delete events
   *
   * List of event IDs to delete
   */
  delete?: Array<number>;
  /**
   * Events
   *
   * List of events to create or update
   */
  events?: Array<EventData>;
};

/**
 * SchedulerResponseModel
 */
export type SchedulerResponseModel = {
  /**
   * Affected events
   *
   * List of event IDs that were affected by this request
   */
  affected_events?: Array<number>;
  /**
   * Affected bins
   *
   * List of bin IDs that were affected by this request
   */
  affected_bins?: Array<number>;
  /**
   * Events
   *
   * List of events
   */
  events?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * ScopedEndpoint
 */
export type ScopedEndpoint = {
  /**
   * Endpoint
   */
  endpoint: string;
  /**
   * Title
   */
  title: string;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * SendRequestModel
 */
export type SendRequestModel = {
  /**
   * Asset IDs
   *
   * List of asset ids
   */
  ids?: Array<number>;
  /**
   * Action ID
   *
   * Action ID
   */
  id_action: number;
  /**
   * Restart existing jobs
   */
  restart_existing?: boolean;
  /**
   * Restart running jobs
   */
  restart_running?: boolean;
  /**
   * Additional job parameters (action specific)
   */
  params?: {
    [key: string]: unknown;
  };
  /**
   * Job priority
   */
  priority?: number;
};

/**
 * SendResponseModel
 */
export type SendResponseModel = {
  /**
   * Job IDs
   *
   * List of job ids created/restarted.
   */
  ids?: Array<number | null>;
};

/**
 * ServiceItemModel
 */
export type ServiceItemModel = {
  /**
   * Service ID
   */
  id: number;
  /**
   * Service name
   */
  name: string;
  /**
   * Service type
   */
  type: string;
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Service status
   *
   * Current status of the service
   */
  status: ServiceState;
  /**
   * Autostart
   */
  autostart: boolean;
  /**
   * Last seen
   *
   * Number of seconds since service was last seen
   */
  last_seen: number;
};

/**
 * ServiceRequestModel
 */
export type ServiceRequestModel = {
  /**
   * Stop ID
   *
   * ID of service to stop
   */
  stop?: number | null;
  /**
   * Start ID
   *
   * ID of service to start
   */
  start?: number | null;
  /**
   * Toggle autostart
   *
   * ID of service to toggle autostart
   */
  auto?: number | null;
};

/**
 * ServiceState
 */
export type ServiceState = 0 | 1 | 2 | 3 | 4;

/**
 * ServicesResponseModel
 */
export type ServicesResponseModel = {
  /**
   * Services
   */
  services?: Array<ServiceItemModel>;
};

/**
 * SessionModel
 */
export type SessionModel = {
  /**
   * User
   *
   * User data
   */
  user: {
    [key: string]: unknown;
  };
  /**
   * Token
   *
   * Access token
   */
  token: string;
  /**
   * Created
   *
   * Creation timestamp
   */
  created: number;
  /**
   * Accessed
   *
   * Last access timestamp
   */
  accessed: number;
  /**
   * Client info
   */
  client_info?: ClientInfo | null;
  /**
   * Transient
   */
  transient?: boolean;
};

/**
 * SolveRequestModel
 */
export type SolveRequestModel = {
  /**
   * Solver
   */
  solver: string;
  /**
   * Items
   *
   * List of placeholder item IDs to solve
   */
  items: Array<number>;
};

/**
 * StorageStat
 */
export type StorageStat = {
  /**
   * Storage Id
   */
  storage_id: number;
  /**
   * Label
   */
  label: string;
  /**
   * Total
   */
  total: number;
  /**
   * Used
   */
  used: number;
  /**
   * Free
   */
  free: number;
  /**
   * Untracked
   */
  untracked: number;
  /**
   * Available
   */
  available?: boolean;
  /**
   * Nebula Usage
   */
  nebula_usage: Array<NebulaStorageUsage>;
  /**
   * Enabled
   */
  enabled?: boolean;
};

/**
 * TemplateItemModel
 */
export type TemplateItemModel = {
  /**
   * Template name
   */
  name: string;
  /**
   * Template title
   */
  title: string;
};

/**
 * TokenExchangeRequestModel
 */
export type TokenExchangeRequestModel = {
  /**
   * Access token
   *
   * Access token to be exchanged for a new one
   */
  access_token: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Full Name
   */
  full_name?: string | null;
};

/**
 * UserModel
 */
export type UserModel = {
  /**
   * Id
   */
  id?: number | null;
  /**
   * Login
   */
  login: string;
  /**
   * Ctime
   */
  ctime?: number;
  /**
   * Mtime
   */
  mtime?: number;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Local Network Only
   */
  local_network_only?: boolean;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Is Limited
   */
  is_limited?: boolean;
  permissions?: UserPermissionsModel;
  /**
   * Password
   */
  password?: string | null;
  /**
   * Api Key
   */
  api_key?: string | null;
};

/**
 * UserPermissionsModel
 *
 * User permission model.
 */
export type UserPermissionsModel = {
  /**
   * Can view assets
   *
   * List of folder IDs user can view. Use 'true' for all folders
   */
  asset_view?: boolean | Array<number>;
  /**
   * Can asset edit
   *
   * List of folder IDs user can edit. Use 'true' for all folders
   */
  asset_edit?: boolean | Array<number>;
  /**
   * Can view rundown
   *
   * List of channel IDs user can view. 'true' for all channels
   */
  rundown_view?: boolean | Array<number>;
  /**
   * Can edit rundown
   *
   * List of channel IDs user can edit. 'true' for all channels
   */
  rundown_edit?: boolean | Array<number>;
  /**
   * Can view scheduler
   *
   * List of channel IDs user can view. 'true' for all channels
   */
  scheduler_view?: boolean | Array<number>;
  /**
   * Can edit scheduler
   *
   * List of channel IDs user can edit. 'true' for all channels
   */
  scheduler_edit?: boolean | Array<number>;
  /**
   * Can control services
   *
   * List of service IDs user can control
   */
  service_control?: boolean | Array<number>;
  /**
   * Can control playout
   *
   * List of channel IDs user can control
   */
  mcr?: boolean | Array<number>;
  /**
   * Can control jobs
   *
   * Use list of action IDs to grant access to specific actions
   */
  job_control?: boolean | Array<number>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * ViewSettings
 */
export type ViewSettings = {
  /**
   * ID
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Position
   */
  position: number;
  /**
   * Folders
   */
  folders?: Array<number> | null;
  /**
   * States
   */
  states?: Array<number> | null;
  /**
   * Columns
   */
  columns?: Array<string> | null;
  /**
   * Conditions
   */
  conditions?: Array<string> | null;
  /**
   * Separator
   */
  separator?: boolean;
};

export type LoginBackgroundApiLoginBackgroundJpgGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/login-background.jpg';
};

export type LoginBackgroundApiLoginBackgroundJpgGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PlayoutData = {
  body: PlayoutRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/playout';
};

export type PlayoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PlayoutError = PlayoutErrors[keyof PlayoutErrors];

export type PlayoutResponses = {
  /**
   * Successful Response
   */
  200: PlayoutResponseModel;
};

export type PlayoutResponse = PlayoutResponses[keyof PlayoutResponses];

export type OpsData = {
  body: OperationsRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/ops';
};

export type OpsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpsError = OpsErrors[keyof OpsErrors];

export type OpsResponses = {
  /**
   * Successful Response
   */
  200: OperationsResponseModel;
};

export type OpsResponse = OpsResponses[keyof OpsResponses];

export type SetData = {
  body: OperationModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/set';
};

export type SetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetError = SetErrors[keyof SetErrors];

export type SetResponses = {
  /**
   * Successful Response
   */
  200: OperationResponseModel;
};

export type SetResponse = SetResponses[keyof SetResponses];

export type DeleteData = {
  body: DeleteRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
    /**
     * X-Client-Id
     */
    'x-client-id'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/delete';
};

export type DeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type BrowseData = {
  body: BrowseRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/browse';
};

export type BrowseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BrowseError = BrowseErrors[keyof BrowseErrors];

export type BrowseResponses = {
  /**
   * Successful Response
   */
  200: BrowseResponseModel;
};

export type BrowseResponse = BrowseResponses[keyof BrowseResponses];

export type StatsStoragesData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/stats/storages';
};

export type StatsStoragesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StatsStoragesError = StatsStoragesErrors[keyof StatsStoragesErrors];

export type StatsStoragesResponses = {
  /**
   * Successful Response
   */
  200: NebulaStoragesUsage;
};

export type StatsStoragesResponse =
  StatsStoragesResponses[keyof StatsStoragesResponses];

export type InvalidateSessionData = {
  body: InvalidateSessionRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/invalidate-session';
};

export type InvalidateSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InvalidateSessionError =
  InvalidateSessionErrors[keyof InvalidateSessionErrors];

export type InvalidateSessionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListSessionsData = {
  body: ListSessionsRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/list-sessions';
};

export type ListSessionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
  /**
   * Response List Sessions
   *
   * Successful Response
   */
  200: Array<SessionModel>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type GetProxyInfoData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/proxy/{id_asset}/info';
};

export type GetProxyInfoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProxyInfoError = GetProxyInfoErrors[keyof GetProxyInfoErrors];

export type GetProxyInfoResponses = {
  /**
   * Successful Response
   */
  200: ProxyInfo;
};

export type GetProxyInfoResponse = GetProxyInfoResponses[keyof GetProxyInfoResponses];

export type ProxyData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/proxy/{id_asset}';
};

export type ProxyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyError = ProxyErrors[keyof ProxyErrors];

export type ProxyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RundownData = {
  body: RundownRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/rundown';
};

export type RundownErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RundownError = RundownErrors[keyof RundownErrors];

export type RundownResponses = {
  /**
   * Successful Response
   */
  200: RundownResponseModel;
};

export type RundownResponse = RundownResponses[keyof RundownResponses];

export type ServicesData = {
  body: ServiceRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/services';
};

export type ServicesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ServicesError = ServicesErrors[keyof ServicesErrors];

export type ServicesResponses = {
  /**
   * Successful Response
   */
  200: ServicesResponseModel;
};

export type ServicesResponse = ServicesResponses[keyof ServicesResponses];

export type ApplySchedulingTemplateData = {
  body: ApplyTemplateRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
    /**
     * X-Client-Id
     */
    'x-client-id'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/apply-scheduling-template';
};

export type ApplySchedulingTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApplySchedulingTemplateError =
  ApplySchedulingTemplateErrors[keyof ApplySchedulingTemplateErrors];

export type ApplySchedulingTemplateResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListSchedulingTemplatesData = {
  body?: never;
  headers?: {
    /**
     * X-Client-Id
     */
    'x-client-id'?: string | null;
  };
  path?: never;
  query?: never;
  url: '/api/list-scheduling-templates';
};

export type ListSchedulingTemplatesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSchedulingTemplatesError =
  ListSchedulingTemplatesErrors[keyof ListSchedulingTemplatesErrors];

export type ListSchedulingTemplatesResponses = {
  /**
   * Successful Response
   */
  200: ListTemplatesResponseModel;
};

export type ListSchedulingTemplatesResponse =
  ListSchedulingTemplatesResponses[keyof ListSchedulingTemplatesResponses];

export type OrderData = {
  body: OrderRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
    /**
     * X-Client-Id
     */
    'x-client-id'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/order';
};

export type OrderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OrderError = OrderErrors[keyof OrderErrors];

export type OrderResponses = {
  /**
   * Successful Response
   */
  200: OrderResponseModel;
};

export type OrderResponse = OrderResponses[keyof OrderResponses];

export type ListUsersData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/list-users';
};

export type ListUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
  /**
   * Successful Response
   */
  200: ListUsersResponseModel;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type SaveUserData = {
  body: UserModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/save-user';
};

export type SaveUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveUserError = SaveUserErrors[keyof SaveUserErrors];

export type SaveUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SolveData = {
  body: SolveRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/solve';
};

export type SolveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SolveError = SolveErrors[keyof SolveErrors];

export type SolveResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LoginData = {
  body: LoginRequestModel;
  path?: never;
  query?: never;
  url: '/api/login';
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: LoginResponseModel;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: '/api/logout';
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SsoCallbackData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: never;
  url: '/api/sso/callback/{provider}';
};

export type SsoCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SsoCallbackError = SsoCallbackErrors[keyof SsoCallbackErrors];

export type SsoCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SsoLoginData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: never;
  url: '/api/sso/login/{provider}';
};

export type SsoLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SsoLoginError = SsoLoginErrors[keyof SsoLoginErrors];

export type SsoLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PasswordData = {
  body: PasswordRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/password';
};

export type PasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PasswordError = PasswordErrors[keyof PasswordErrors];

export type PasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TokenExchangeData = {
  body: TokenExchangeRequestModel;
  path?: never;
  query?: never;
  url: '/api/token-exchange';
};

export type TokenExchangeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TokenExchangeError = TokenExchangeErrors[keyof TokenExchangeErrors];

export type TokenExchangeResponses = {
  /**
   * Successful Response
   */
  200: LoginResponseModel;
};

export type TokenExchangeResponse =
  TokenExchangeResponses[keyof TokenExchangeResponses];

export type GetData = {
  body: GetRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/get';
};

export type GetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
  /**
   * Successful Response
   */
  200: GetResponseModel;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type UploadData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path: {
    /**
     * Id Asset
     */
    id_asset: number;
  };
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/upload/{id_asset}';
};

export type UploadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadError = UploadErrors[keyof UploadErrors];

export type UploadResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type InitData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
  };
  url: '/api/init';
};

export type InitErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InitError = InitErrors[keyof InitErrors];

export type InitResponses = {
  /**
   * Successful Response
   */
  200: InitResponseModel;
};

export type InitResponse = InitResponses[keyof InitResponses];

export type ActionsData = {
  body: ActionsRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/actions';
};

export type ActionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ActionsError = ActionsErrors[keyof ActionsErrors];

export type ActionsResponses = {
  /**
   * Successful Response
   */
  200: ActionsResponseModel;
};

export type ActionsResponse = ActionsResponses[keyof ActionsResponses];

export type JobsData = {
  body: JobsRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/jobs';
};

export type JobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type JobsError = JobsErrors[keyof JobsErrors];

export type JobsResponses = {
  /**
   * Successful Response
   */
  200: JobsResponseModel;
};

export type JobsResponse = JobsResponses[keyof JobsResponses];

export type SendData = {
  body: SendRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/send';
};

export type SendErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendError = SendErrors[keyof SendErrors];

export type SendResponses = {
  /**
   * Successful Response
   */
  200: SendResponseModel;
};

export type SendResponse = SendResponses[keyof SendResponses];

export type SchedulerData = {
  body: SchedulerRequestModel;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
    /**
     * X-Client-Id
     */
    'x-client-id'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/scheduler';
};

export type SchedulerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SchedulerError = SchedulerErrors[keyof SchedulerErrors];

export type SchedulerResponses = {
  /**
   * Successful Response
   */
  200: SchedulerResponseModel;
};

export type SchedulerResponse = SchedulerResponses[keyof SchedulerResponses];

export type SharelinkData = {
  body: ContextTestRequest;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/sharelink';
};

export type SharelinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SharelinkError = SharelinkErrors[keyof SharelinkErrors];

export type SharelinkResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EpgData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Id Channel
     */
    id_channel?: number;
  };
  url: '/api/epg';
};

export type EpgErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EpgError = EpgErrors[keyof EpgErrors];

export type EpgResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MarkdownTranscriptionData = {
  body: ContextTestRequest;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/markdown_transcription';
};

export type MarkdownTranscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MarkdownTranscriptionError =
  MarkdownTranscriptionErrors[keyof MarkdownTranscriptionErrors];

export type MarkdownTranscriptionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TranscriptionData = {
  body?: never;
  path: {
    /**
     * Guid
     */
    guid: string;
  };
  query?: never;
  url: '/api/transcription/{guid}';
};

export type TranscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TranscriptionError = TranscriptionErrors[keyof TranscriptionErrors];

export type TranscriptionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LineupData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Channel ID
     */
    id_channel?: number;
    /**
     * As timestamp
     *
     * Show as it would return at the given timestamp
     */
    as_timestamp?: number | null;
    /**
     * Limit
     */
    limit?: number | null;
  };
  url: '/api/lineup';
};

export type LineupErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LineupError = LineupErrors[keyof LineupErrors];

export type LineupResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AdsUtilizationData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Date
     */
    date?: string | null;
    /**
     * Id Channel
     */
    id_channel?: number;
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/ads_utilization';
};

export type AdsUtilizationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdsUtilizationError = AdsUtilizationErrors[keyof AdsUtilizationErrors];

export type AdsUtilizationResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AsrunxlsData = {
  body: AsrunXlsRequest;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/asrunxls';
};

export type AsrunxlsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AsrunxlsError = AsrunxlsErrors[keyof AsrunxlsErrors];

export type AsrunxlsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type WebsyncData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Last
     */
    last?: number;
  };
  url: '/api/websync';
};

export type WebsyncErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WebsyncError = WebsyncErrors[keyof WebsyncErrors];

export type WebsyncResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AssetRunsData = {
  body: ContextTestRequest;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/asset_runs';
};

export type AssetRunsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AssetRunsError = AssetRunsErrors[keyof AssetRunsErrors];

export type AssetRunsResponses = {
  /**
   * Successful Response
   */
  200: ContextPluginResponseModel;
};

export type AssetRunsResponse = AssetRunsResponses[keyof AssetRunsResponses];

export type AssignmentsData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
    /**
     * X-Api-Key
     */
    'x-api-key'?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Token
     */
    token?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
  };
  url: '/api/assignments';
};

export type AssignmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AssignmentsError = AssignmentsErrors[keyof AssignmentsErrors];

export type AssignmentsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
