"""Generate descriptive metadata for an asset using TwelveLabs Pegasus.

This is an opt-in integration: it is only available when
``NEBULA_TWELVELABS_API_KEY`` is configured. It uploads the asset's local
media (proxy preferred, original as a fallback) to TwelveLabs, runs the
Pegasus video-understanding model, and stores the generated description in
the ``aux`` table under the ``twelvelabs:analysis`` key so it can be reused
later (e.g. for cataloguing or search).

A free API key with a generous free tier is available at https://twelvelabs.io
"""

import asyncio
import time
from typing import Annotated

import anyio
from pydantic import Field
from twelvelabs import TwelveLabs
from twelvelabs.types.video_context import VideoContext_AssetId

import nebula
from api.media.proxy import get_proxy_path
from server.dependencies import CurrentUser
from server.models import RequestModel
from server.request import APIRequest

DEFAULT_PROMPT = (
    "You are cataloguing a video for a broadcast media asset management "
    "system. Describe the content: the subject, what happens, the setting, "
    "any people, on-screen text and the overall mood. Be concise and factual."
)


class AnalyzeTwelveLabsRequest(RequestModel):
    id_asset: int = Field(..., description="Asset ID")
    prompt: Annotated[
        str | None,
        Field(
            description="Optional custom prompt for the Pegasus model. "
            "Defaults to a generic cataloguing prompt.",
        ),
    ] = None
    max_tokens: Annotated[
        int,
        Field(
            description="Maximum number of tokens in the response",
            ge=512,
            le=4096,
        ),
    ] = 2048


class AnalyzeTwelveLabsResponse(RequestModel):
    text: Annotated[
        str,
        Field(description="The description generated by the Pegasus model"),
    ]


def analyze_media(video_path: str, prompt: str, max_tokens: int, model: str) -> str:
    """Upload the media and run Pegasus. Blocking; run in a worker thread."""
    client = TwelveLabs(api_key=nebula.config.twelvelabs_api_key)

    with open(video_path, "rb") as f:
        asset = client.assets.create(method="direct", file=f)

    if not asset.id:
        raise RuntimeError("TwelveLabs did not return an asset id")

    # The uploaded asset must finish processing before it can be analyzed.
    deadline = time.monotonic() + 600
    while True:
        detail = client.assets.retrieve(asset.id)
        if detail.status == "ready":
            break
        if detail.status == "failed":
            raise RuntimeError("TwelveLabs failed to process the uploaded media")
        if time.monotonic() > deadline:
            raise TimeoutError("Timed out waiting for TwelveLabs to process the media")
        time.sleep(5)

    response = client.analyze(
        model_name=model,
        video=VideoContext_AssetId(asset_id=asset.id),
        prompt=prompt,
        max_tokens=max_tokens,
    )
    return (response.data or "").strip()


class AnalyzeTwelveLabs(APIRequest):
    """Generate descriptive metadata for an asset using TwelveLabs Pegasus.

    Requires `NEBULA_TWELVELABS_API_KEY` to be configured. The generated
    description is also stored in the `aux` table under the
    `twelvelabs:analysis` key.
    """

    name: str = "analyze_twelvelabs"
    title: str = "Analyze with TwelveLabs"
    category = "Asset management"

    async def handle(
        self,
        payload: AnalyzeTwelveLabsRequest,
        user: CurrentUser,
    ) -> AnalyzeTwelveLabsResponse:

        if not nebula.config.twelvelabs_api_key:
            raise nebula.NotImplementedException(
                "TwelveLabs integration is not configured. "
                "Set NEBULA_TWELVELABS_API_KEY to enable it."
            )

        asset = await nebula.Asset.load(payload.id_asset)

        if not user.is_admin:
            acl = user.get("can/asset_edit", False)
            if not acl:
                raise nebula.ForbiddenException("You are not allowed to edit assets")
            if isinstance(acl, list) and asset["id_folder"] not in acl:
                raise nebula.ForbiddenException(
                    "You are not allowed to edit assets in this folder"
                )

        # Prefer the low-res proxy (smaller upload), fall back to the original.
        proxy_path = get_proxy_path(payload.id_asset)
        if await anyio.Path(proxy_path).exists():
            video_path: str | None = proxy_path
        else:
            video_path = asset.path
        if not video_path or not await anyio.Path(video_path).exists():
            raise nebula.NotFoundException("No media file available for this asset")

        try:
            text = await asyncio.to_thread(
                analyze_media,
                video_path,
                payload.prompt or DEFAULT_PROMPT,
                payload.max_tokens,
                nebula.config.twelvelabs_model,
            )
        except (RuntimeError, TimeoutError) as exc:
            raise nebula.NebulaException(str(exc)) from exc

        query = """
            INSERT INTO aux (key, object_type, id_object, data)
            VALUES ('twelvelabs:analysis', 0, $1, $2)
            ON CONFLICT (key, object_type, id_object) DO UPDATE
            SET data = EXCLUDED.data
        """
        await nebula.db.execute(
            query,
            payload.id_asset,
            {"model": nebula.config.twelvelabs_model, "text": text},
        )

        return AnalyzeTwelveLabsResponse(text=text)
